version: '3'
services:
  db:
    restart: unless-stopped
    image: galien0xffffff/postgres-debugger:14
    ports:
      - "${PGPORT:-5433}:5432"
    environment:
      POSTGRES_DB: "${PGDATABASE:-blueraven}"
      POSTGRES_USER: "${PGUSER:-dbadmin}"
      POSTGRES_PASSWORD: "${PGPASSWORD:-password}"

  redis:
    restart: unless-stopped
    image: redis:latest
    ports:
      - "6379:6379"
