version: '3'
services:
  db:
    restart: always
    image: postgres:11.4-alpine
    expose:
      - "5433"
    ports:
      - "${PGPORT}:5432"

    environment:
      POSTGRES_DB: "${PGDATABASE}"
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"


  sign-proxy:
    image: codekoala/aws-sign-proxy:v0.1.4
    environment:
        AWS_ACCESS_KEY_ID: "${LOANPAL_ACCESS_KEY_ID}"
        AWS_SECRET_ACCESS_KEY: "${LOANPAL_SECRET_ACCESS_KEY}"
        AWS_SIGN_PROXY_TARGETHOST: "${AWS_SIGN_PROXY_TARGETHOST}"
        AWS_SIGN_PROXY_PROVIDER: "${AWS_SIGN_PROXY_PROVIDER}"
        AWS_SIGN_PROXY_REGION: "${AWS_SIGN_PROXY_REGION}"
        AWS_SIGN_PROXY_BLOCKHEADERS: "connection"
    ports:
        - "8081:8080"
