version: '3'
services:
  db:
    restart: unless-stopped
    image: galien0xffffff/postgres-debugger:14
    ports:
      - "${PGPORT:-5433}:5432"
    environment:
      POSTGRES_DB: "${PGDATABASE:-blueraven}"
      POSTGRES_USER: "${PGUSER:-dbadmin}"
      POSTGRES_PASSWORD: "${PGPASSWORD:-password}"

  redis:
    restart: unless-stopped
    image: redis:latest
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack-s3-volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  gotenberg:
    image: gotenberg/gotenberg:7
    ports:
      - 4000:3000
