[build]
  base  = "client"
  publish = "dist/"
  ignore = "git diff --quiet HEAD^ HEAD ."

[build.environment]
  NODE_VERSION = "12.18.3"

[context.release]
  publish = "client/dist/"

[context.master]
    publish = "client/dist/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
