[build]
  base  = "client"
  publish = "dist/"
  ignore = "git diff --quiet HEAD^ HEAD ."

[context.stage]
  publish = "client/dist/"

[context.release]
  publish = "client/dist/"

[context.master]
    publish = "client/dist/"
