Description: >
Parameters:
  VpcId:
    Description: The VPC to which this cluster should be deployed
    Type: AWS::EC2::VPC::Id

  Subnets:
    Description: Choose at least two subnets in this VPC
    Type: List<AWS::EC2::Subnet::Id>

  SecurityGroup:
    Description: The VPC to which this cluster should be deployed
    Type: List<AWS::EC2::SecurityGroup::Id>

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/prometheus
  
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: prometheus-cluster

  TaskDefinition: 
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: prometheus-td
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      ExecutionRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole
      Memory: 512
      Cpu: 256
      ContainerDefinitions:
        -
          Name: prometheus-container
          Image: prom/prometheus
          Memory: 512
          Cpu: 256
          PortMappings:
            -
              ContainerPort: 9090
          LogConfiguration:
            LogDriver: awslogs
            Options:
                awslogs-group: "/ecs/prometheus"
                awslogs-region: !Ref AWS::Region
                awslogs-stream-prefix: "prometheus"

  ServiceDefinition:
    Type: AWS::ECS::Service
    Properties:
      LaunchType: FARGATE
      TaskDefinition: !Ref TaskDefinition
      Cluster: !Ref ECSCluster
      ServiceName: prometheus-service
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref Subnets
          SecurityGroups: !Ref SecurityGroup
