-- capture the configs

-- select *
-- from flow.event;
-- -- 69,DO NOT TOUCH - Permit Signature
-- -- 68,DO NOT TOUCH - Permit Pickup and Delivery
-- -- 67,DO NOT TOUCH - Online Permit Submission
-- -- 66,DO NOT TOUCH - In Person Permit Submission
-- select *
-- from flow.event_attachment_type
-- where event_id in (66,67,68,69);
-- select pseaf.*
-- from flow.process_step_event_action_field pseaf
--   inner join flow.process_step_event_action psea on pseaf.process_step_event_action_id = psea.id
-- inner join flow.process_step_event pse on psea.process_step_event_id = pse.id
-- WHERE pse.event_id in (66,67,68,69);
-- select psel.*
-- from flow.event_requirement_param_dynamic_value psel
-- inner join  flow.process_step_event_requirement pser on psel.process_step_event_requirement_id = pser.id
-- inner join flow.process_step_event pse on pser.process_step_event_id = pse.id
-- WHERE pse.event_id in (66,67,68,69);
-- select *
-- from flow.event_requirement_param_dynamic_value;
-- select *
-- from flow.custom_field_group
-- WHERE event_id in (66,67,68,69);
-- select DISTINCT list_of_value_id
-- from flow.custom_field_group_assignment cfga
--   inner join flow.custom_field cf on cfga.custom_field_id = cf.id
-- inner join flow.custom_field_group cfg on cfga.custom_field_group_id = cfg.id
-- WHERE event_id in (66,67,68,69);
-- select CFOT.*
-- from flow.custom_field_object_type cfot
-- inner join flow.company_object_type cot on cfot.company_object_type_id = cot.id
-- where company_id = 3 and object_type_id = 6
-- and custom_field_id in (11358,11354,11350,392,11353,11351,11352,11350,392,11351,11352,11355,11356,11353,11357);
-- select *
-- from flow.company_object_type
-- where company_id = 3;
-- select *
-- from flow.list_of_value
-- where id in (19833, 19837) or parent_id in (19833, 19837);
--
-- select *
-- from flow.custom_field
-- where id in (392,11350,11351,11352,11353,11354,11355,11356,11357,11358)
-- ;
-- select *
-- from flow.list_of_value;
-- @randa @keller START HERE
-- EVENTS:
-- INSERT INTO flow.event (event_name, resource_custom_field_id, company_id, date_created, date_modified, created_by_id, modified_by_id, archived, temp_cfg_id) VALUES ('DO NOT TOUCH - Permit Signature', 11359, 3, '2021-08-27 22:23:33.933194', null, 2356764, null, false, null);
-- INSERT INTO flow.event (event_name, resource_custom_field_id, company_id, date_created, date_modified, created_by_id, modified_by_id, archived, temp_cfg_id) VALUES ('DO NOT TOUCH - Permit Pickup and Delivery', 247, 3, '2021-08-27 22:12:10.910605', '2021-08-27 22:12:23.245748', 2356764, 2356764, false, null);
-- INSERT INTO flow.event (event_name, resource_custom_field_id, company_id, date_created, date_modified, created_by_id, modified_by_id, archived, temp_cfg_id) VALUES ('DO NOT TOUCH - Online Permit Submission', 11349, 3, '2021-08-27 22:11:14.516982', null, 2356764, null, false, null);
-- INSERT INTO flow.event (event_name, resource_custom_field_id, company_id, date_created, date_modified, created_by_id, modified_by_id, archived, temp_cfg_id) VALUES ('DO NOT TOUCH - In Person Permit Submission', 11348, 3, '2021-08-27 22:02:32.405101', '2021-08-27 22:02:38.105738', 2356764, 2356764, false, null);
-- LIST OF VALUES with their custom fields
-- with parent_lov as (
--   INSERT INTO flow.list_of_value (name, code, parent_id, display_order, date_created, date_modified, created_by_id, modified_by_id, archived, migrated_original_id, migrated_company_id)
--   VALUES ('Event Outcome', null, null, 0, '2021-08-27 22:07:43.802669', null, 2356764, null, false, null, null)
--   returning id
-- ), child_lov_1 as (
--   INSERT INTO flow.list_of_value (name, code, parent_id, display_order, date_created, date_modified, created_by_id, modified_by_id, archived, migrated_original_id, migrated_company_id)
--     VALUES ('Permit Submitted', null, (select id from parent_lov), 0, '2021-08-27 22:07:43.804367', '2021-08-27 22:16:18.405520', 2356764, 2356764, false, null, null)
-- ), child_lov_2 as (
--   INSERT INTO flow.list_of_value (name, code, parent_id, display_order, date_created, date_modified, created_by_id, modified_by_id, archived, migrated_original_id, migrated_company_id)
--     VALUES ('Permit Not Submitted - Technician No Show', null, (select id from parent_lov), 1, '2021-08-27 22:07:43.805709', '2021-08-27 22:16:18.406860', 2356764, 2356764, false, null, null)
-- ), child_lov_3 as (
--   INSERT INTO flow.list_of_value (name, code, parent_id, display_order, date_created, date_modified, created_by_id, modified_by_id, archived, migrated_original_id, migrated_company_id)
--   VALUES ('Permit Not Submitted - Other', null, (select id from parent_lov), 2, '2021-08-27 22:07:43.806974', '2021-08-27 22:16:18.408067', 2356764, 2356764, false, null, null)
-- ) -- then insert the custom field with the appropriate list of value
-- INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key, readonly, migrated_original_id, parent_custom_field_id)
-- values ((select id from parent_lov), 3, 'Permit Submission Event Outcome', 7, '2021-08-27 22:07:43.809448', '2021-08-27 22:16:18.403989', 2356764, 2356764, false, null, null, null, null, false, null, null);
--
-- with parent_lov as (
--   INSERT INTO flow.list_of_value (name, code, parent_id, display_order, date_created, date_modified, created_by_id, modified_by_id, archived, migrated_original_id, migrated_company_id)
--     VALUES ('Permit Pickup and Delivery Event Outcome', null, null, 0, '2021-08-27 22:17:09.198700', null, 2356764, null, false, null, null)
--     returning id
-- ), child_lov_1 as (
--   INSERT INTO flow.list_of_value (name, code, parent_id, display_order, date_created, date_modified, created_by_id, modified_by_id, archived, migrated_original_id, migrated_company_id)
--     VALUES ('Permit On Site', null, (select id from parent_lov), 0, '2021-08-27 22:17:09.200148', null, 2356764, null, false, null, null)
-- ), child_lov_2 as (
-- INSERT INTO flow.list_of_value (name, code, parent_id, display_order, date_created, date_modified, created_by_id, modified_by_id, archived, migrated_original_id, migrated_company_id)
--   VALUES ('Permit Not On Site - Technician No Show', null, (select id from parent_lov), 1, '2021-08-27 22:17:09.201387', null, 2356764, null, false, null, null)
-- ), child_lov_3 as (
--   INSERT INTO flow.list_of_value (name, code, parent_id, display_order, date_created, date_modified, created_by_id, modified_by_id, archived, migrated_original_id, migrated_company_id)
-- VALUES ('Permit Not On Site - Other', null, (select id from parent_lov), 2, '2021-08-27 22:17:09.202630', null, 2356764, null, false, null, null)
-- ) -- then insert the custom field with the appropriate list of value
-- INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key, readonly, migrated_original_id, parent_custom_field_id)
-- VALUES ((select id from parent_lov), 3, 'Permit Pickup and Delivery Event Outcome', 7, '2021-08-27 22:17:09.205111', null, 2356764, null, false, null, null, null, null, false, null, null);
-- -- CUSTOM FIELDS -non-lov
-- INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key, readonly, migrated_original_id, parent_custom_field_id) VALUES (null, 3, 'Permit Pickup Scheduled By', 10, '2021-08-27 22:13:06.331713', null, 2356764, null, false, 2, '{165,168,173}', null, null, false, null, null);
-- INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key, readonly, migrated_original_id, parent_custom_field_id) VALUES (null, 3, 'Permit Signature Scheduled By', 10, '2021-08-27 22:15:20.519558', null, 2356764, null, false, 2, '{165,168,173}', null, null, false, null, null);
-- CUSTOM FIELD OBJECT TYPE RELATION
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES ((select id from flow.custom_field where company_id = 3 and field_name = 'AHJ'), (select id from flow.company_object_type where company_id = 3 and object_type_id = 6), false, '2021-08-26 20:31:07.469339', null, 2350555, null);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES ((select id from flow.custom_field where company_id = 3 and field_name = 'Permit Type'), (select id from flow.company_object_type where company_id = 3 and object_type_id = 6), false, '2021-08-27 22:04:28.065036', null, 2356764, null);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES ((select id from flow.custom_field where company_id = 3 and field_name = 'Permit Decision'), (select id from flow.company_object_type where company_id = 3 and object_type_id = 6), false, '2021-08-27 22:06:29.231664', null, 2356764, null);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES ((select id from flow.custom_field where company_id = 3 and field_name = 'Permit Decision Verified By'), (select id from flow.company_object_type where company_id = 3 and object_type_id = 6), false, '2021-08-27 22:06:52.254939', null, 2356764, null);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES ((select id from flow.custom_field where company_id = 3 and field_name = 'Permit Submission Event Outcome'), (select id from flow.company_object_type where company_id = 3 and object_type_id = 6), false, '2021-08-27 22:07:43.818773', '2021-08-27 22:16:18.427308', 2356764, 2356764);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES ((select id from flow.custom_field where company_id = 3 and field_name = 'permit Submission Scheduled By'), (select id from flow.company_object_type where company_id = 3 and object_type_id = 6), false, '2021-08-27 22:08:28.587928', null, 2356764, null);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES ((select id from flow.custom_field where company_id = 3 and field_name = 'Permit Pickup Scheduled By'), (select id from flow.company_object_type where company_id = 3 and object_type_id = 6), false, '2021-08-27 22:13:06.341550', null, 2356764, null);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES ((select id from flow.custom_field where company_id = 3 and field_name = 'Permit Signature Scheduled By'), (select id from flow.company_object_type where company_id = 3 and object_type_id = 6), false, '2021-08-27 22:15:20.529274', null, 2356764, null);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES ((select id from flow.custom_field where company_id = 3 and field_name = 'Permit Pickup and Delivery Event Outcome'), (select id from flow.company_object_type where company_id = 3 and object_type_id = 6), false, '2021-08-27 22:17:09.213083', null, 2356764, null);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES ((select id from flow.custom_field where company_id = 3 and field_name = 'Permit Signature Event Outcome'), (select id from flow.company_object_type where company_id = 3 and object_type_id = 6), false, '2021-08-27 22:19:05.038825', null, 2356764, null);
-- CUSTOM FIELD GROUPS
INSERT INTO flow.custom_field_group (group_name, company_object_type_id, group_order, archived, process_step_id, event_type_id, date_created, date_modified, created_by_id, modified_by_id, migrated_original_id, migrated_company_id, company_object_type_tab_id, unique_behavior_type_id, event_id) VALUES ('Permit Details', (select id from flow.company_object_type where company_id = 3 and object_type_id = 6), 5, false, null, null, '2021-08-27 22:03:16.533504', null, 2356764, null, null, null, null, null, (select id from flow.event where event_name = 'DO NOT TOUCH - In Person Permit Submission' and company_id = 3));
INSERT INTO flow.custom_field_group (group_name, company_object_type_id, group_order, archived, process_step_id, event_type_id, date_created, date_modified, created_by_id, modified_by_id, migrated_original_id, migrated_company_id, company_object_type_tab_id, unique_behavior_type_id, event_id) VALUES ('Permit Details', (select id from flow.company_object_type where company_id = 3 and object_type_id = 6), 6, false, null, null, '2021-08-27 22:11:20.966214', null, 2356764, null, null, null, null, null, (select id from flow.event where event_name = 'DO NOT TOUCH - Online Permit Submission' and company_id = 3));
INSERT INTO flow.custom_field_group (group_name, company_object_type_id, group_order, archived, process_step_id, event_type_id, date_created, date_modified, created_by_id, modified_by_id, migrated_original_id, migrated_company_id, company_object_type_tab_id, unique_behavior_type_id, event_id) VALUES ('Permit Pickup Details', (select id from flow.company_object_type where company_id = 3 and object_type_id = 6), 7, false, null, null, '2021-08-27 22:12:33.472734', null, 2356764, null, null, null, null, null, (select id from flow.event where event_name = 'DO NOT TOUCH - Permit Pickup and Delivery' and company_id = 3));
INSERT INTO flow.custom_field_group (group_name, company_object_type_id, group_order, archived, process_step_id, event_type_id, date_created, date_modified, created_by_id, modified_by_id, migrated_original_id, migrated_company_id, company_object_type_tab_id, unique_behavior_type_id, event_id) VALUES ('Permit Signature Details', (select id from flow.company_object_type where company_id = 3 and object_type_id = 6), 8, false, null, null, '2021-08-27 22:24:35.188822', null, 2356764, null, null, null, null, null, (select id from flow.event where event_name = 'DO NOT TOUCH - Permit Signature' and company_id = 3));
-- CUSTOM FIELD GROUP ASSIGNMENTS
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id, read_only, migrated_original_id, migrated_company_id, use_parent_data, hidden, detail_view)
VALUES ((select id from flow.custom_field_group where group_name = 'Permit Pickup Details' and event_id = (select id from flow.event where event_name = 'DO NOT TOUCH - Permit Pickup and Delivery' and company_id = 3)), (select id from flow.custom_field where field_name = 'Permit Pickup Scheduled By' and company_id = 3), null, 0, false, '2021-08-27 22:13:15.335830', null, 2356764, null, null, false, null, null, false, false, false);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id, read_only, migrated_original_id, migrated_company_id, use_parent_data, hidden, detail_view)
VALUES ((select id from flow.custom_field_group where group_name = 'Permit Pickup Details' and event_id = (select id from flow.event where event_name = 'DO NOT TOUCH - Permit Pickup and Delivery' and company_id = 3)), (select id from flow.custom_field where field_name = 'Permit Submission Event Outcome' and company_id = 3), null, 1, true, '2021-08-27 22:13:21.335391', '2021-09-02 19:30:27.671915', 2356764, 2356764, null, false, null, null, false, false, false);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id, read_only, migrated_original_id, migrated_company_id, use_parent_data, hidden, detail_view)
VALUES ((select id from flow.custom_field_group where group_name = 'Permit Pickup Details' and event_id = (select id from flow.event where event_name = 'DO NOT TOUCH - Permit Pickup and Delivery' and company_id = 3)), (select id from flow.custom_field where field_name = 'Permit Pickup and Delivery Event Outcome' and company_id = 3), null, 2, false, '2021-09-02 19:30:24.297488', null, 2356764, null, null, false, null, null, false, false, false);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id, read_only, migrated_original_id, migrated_company_id, use_parent_data, hidden, detail_view)
VALUES ((select id from flow.custom_field_group where group_name = 'Permit Signature Details' and event_id = (select id from flow.event where event_name = 'DO NOT TOUCH - Permit Signature' and company_id = 3)), (select id from flow.custom_field where field_name = 'Permit Signature Scheduled By' and company_id = 3), null, 0, false, '2021-08-27 22:24:42.715335', null, 2356764, null, null, false, null, null, false, false, false);
-- EVENT ATTACHMENTS
INSERT INTO flow.event_attachment_type (attachment_type_id, event_id, read_only, date_created, date_modified, display_order, created_by_id, modified_by_id, archived) VALUES ((select id from flow.attachment_type where company_id = 3 and attachment_type = 'Permission to Operate'), (select id from flow.event where event_name = 'DO NOT TOUCH - In Person Permit Submission' and company_id = 3), false, '2021-08-31 17:06:27.049546', '2021-08-31 17:06:30.783350', 1, 2356764, 2356764, true);
INSERT INTO flow.event_attachment_type (attachment_type_id, event_id, read_only, date_created, date_modified, display_order, created_by_id, modified_by_id, archived) VALUES ((select id from flow.attachment_type where company_id = 3 and attachment_type = 'Permission to Operate'), (select id from flow.event where event_name = 'DO NOT TOUCH - In Person Permit Submission' and company_id = 3), false, '2021-08-31 17:06:26.971746', '2021-08-31 17:06:33.106831', 0, 2356764, 2356764, true);
INSERT INTO flow.event_attachment_type (attachment_type_id, event_id, read_only, date_created, date_modified, display_order, created_by_id, modified_by_id, archived) VALUES ((select id from flow.attachment_type where company_id = 3 and attachment_type = 'Permit Pack'), (select id from flow.event where event_name = 'DO NOT TOUCH - In Person Permit Submission' and company_id = 3), false, '2021-08-31 17:06:41.646856', null, 0, 2356764, null, false);
INSERT INTO flow.event_attachment_type (attachment_type_id, event_id, read_only, date_created, date_modified, display_order, created_by_id, modified_by_id, archived) VALUES ((select id from flow.attachment_type where company_id = 3 and attachment_type = 'Permit Pack'), (select id from flow.event where event_name = 'DO NOT TOUCH - Online Permit Submission' and company_id = 3), false, '2021-08-31 17:11:07.846649', null, 0, 2356764, null, false);
INSERT INTO flow.event_attachment_type (attachment_type_id, event_id, read_only, date_created, date_modified, display_order, created_by_id, modified_by_id, archived) VALUES ((select id from flow.attachment_type where company_id = 3 and attachment_type = 'Permission to Operate'), (select id from flow.event where event_name = 'DO NOT TOUCH - Permit Pickup and Delivery' and company_id = 3), false, '2021-08-31 17:15:34.227494', '2021-08-31 17:19:05.227496', 0, 2356764, 2356764, true);
INSERT INTO flow.event_attachment_type (attachment_type_id, event_id, read_only, date_created, date_modified, display_order, created_by_id, modified_by_id, archived) VALUES ((select id from flow.attachment_type where company_id = 3 and attachment_type = 'Permission to Operate'), (select id from flow.event where event_name = 'DO NOT TOUCH - Permit Pickup and Delivery' and company_id = 3), false, '2021-08-31 17:15:34.228249', '2021-08-31 17:19:06.668602', 0, 2356764, 2356764, true);
INSERT INTO flow.event_attachment_type (attachment_type_id, event_id, read_only, date_created, date_modified, display_order, created_by_id, modified_by_id, archived) VALUES ((select id from flow.attachment_type where company_id = 3 and attachment_type = 'Permission to Operate'), (select id from flow.event where event_name = 'DO NOT TOUCH - Permit Pickup and Delivery' and company_id = 3), false, '2021-08-31 17:15:34.228899', '2021-08-31 17:19:08.186150', 0, 2356764, 2356764, true);
INSERT INTO flow.event_attachment_type (attachment_type_id, event_id, read_only, date_created, date_modified, display_order, created_by_id, modified_by_id, archived) VALUES ((select id from flow.attachment_type where company_id = 3 and attachment_type = 'Permission to Operate'), (select id from flow.event where event_name = 'DO NOT TOUCH - Permit Pickup and Delivery' and company_id = 3), false, '2021-08-31 17:15:34.293267', '2021-08-31 17:19:09.632792', 1, 2356764, 2356764, true);
INSERT INTO flow.event_attachment_type (attachment_type_id, event_id, read_only, date_created, date_modified, display_order, created_by_id, modified_by_id, archived) VALUES ((select id from flow.attachment_type where company_id = 3 and attachment_type = 'Permit Pack'), (select id from flow.event where event_name = 'DO NOT TOUCH - Permit Pickup and Delivery' and company_id = 3), false, '2021-08-31 17:19:13.935105', null, 0, 2356764, null, false);
INSERT INTO flow.event_attachment_type (attachment_type_id, event_id, read_only, date_created, date_modified, display_order, created_by_id, modified_by_id, archived) VALUES ((select id from flow.attachment_type where company_id = 3 and attachment_type = 'Permit Pack'), (select id from flow.event where event_name = 'DO NOT TOUCH - Permit Signature' and company_id = 3), false, '2021-08-31 17:28:38.887847', null, 0, 2356764, null, false);
-- COMPANY EVENT STATUSES
INSERT INTO flow.company_event_status_type (event_status_type_id, event_status_type, company_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES (1, 'Ready to Schedule', 3, false, '2021-08-25 20:02:40.888231', null, 2350555, null);
INSERT INTO flow.company_event_status_type (event_status_type_id, event_status_type, company_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES (1, 'Scheduled', 3, false, '2021-08-25 20:07:03.577890', null, 2350555, null);
INSERT INTO flow.company_event_status_type (event_status_type_id, event_status_type, company_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES (2, 'Complete', 3, false, '2021-08-25 20:07:16.107215', '2021-08-31 17:40:55.050209', 2350555, 2356764);
INSERT INTO flow.company_event_status_type (event_status_type_id, event_status_type, company_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES (2, 'Passed', 3, false, '2021-08-26 20:29:14.379818', null, 2350555, null);
INSERT INTO flow.company_event_status_type (event_status_type_id, event_status_type, company_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES (2, 'Failed', 3, false, '2021-08-26 20:29:25.976499', null, 2350555, null);
INSERT INTO flow.company_event_status_type (event_status_type_id, event_status_type, company_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES (3, 'Rescheduled', 3, false, '2021-08-26 20:29:38.806659', null, 2350555, null);
INSERT INTO flow.company_event_status_type (event_status_type_id, event_status_type, company_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES (1, 'Ready to Submit', 3, false, '2021-08-31 16:18:29.832698', null, 2356764, null);
INSERT INTO flow.company_event_status_type (event_status_type_id, event_status_type, company_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES (1, 'Pending', 3, false, '2021-08-31 16:18:54.736091', null, 2356764, null);
INSERT INTO flow.company_event_status_type (event_status_type_id, event_status_type, company_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES (1, 'Ready to Verify', 3, false, '2021-08-31 17:04:30.407423', '2021-08-31 17:15:11.701436', 2356764, 2356764);
INSERT INTO flow.company_event_status_type (event_status_type_id, event_status_type, company_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES (3, 'Not Complete - No Show', 3, false, '2021-08-31 17:05:07.165588', '2021-08-31 17:05:41.603564', 2356764, 2356764);
INSERT INTO flow.company_event_status_type (event_status_type_id, event_status_type, company_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES (3, 'Not Complete - Other', 3, false, '2021-08-31 17:05:33.167514', null, 2356764, null);
INSERT INTO flow.company_event_status_type (event_status_type_id, event_status_type, company_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES (1, 'Pending Approval', 3, false, '2021-08-31 17:09:57.846660', null, 2356764, null);
INSERT INTO flow.company_event_status_type (event_status_type_id, event_status_type, company_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES (2, 'Approved', 3, false, '2021-08-31 17:10:03.479894', null, 2356764, null);
INSERT INTO flow.company_event_status_type (event_status_type_id, event_status_type, company_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES (2, 'Rejected', 3, false, '2021-08-31 17:10:09.500698', null, 2356764, null);
INSERT INTO flow.company_event_status_type (event_status_type_id, event_status_type, company_id, archived, date_created, date_modified, created_by_id, modified_by_id) VALUES (3, 'Cancelled', 3, false, '2021-08-31 17:10:52.005565', null, 2356764, null);
-- event company event statuses
select *
from flow.event
  where id in (66,67,68,69)
order by id;
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Ready to Schedule'), '2021-08-31 16:18:40.043524', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Pending'), '2021-08-31 16:19:31.855633', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Ready to Verify'), '2021-08-31 17:04:37.134462', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Not Complete - Other'), '2021-08-31 17:05:55.085613', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Ready to Submit'), '2021-08-31 17:09:23.955836', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Pending Approval'), '2021-08-31 17:10:25.179459', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Approved'), '2021-08-31 17:10:28.395394', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Rejected'), '2021-08-31 17:10:32.502501', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Cancelled'), '2021-08-31 17:10:56.756617', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Pending Approval'), '2021-08-31 17:13:59.939659', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Approved'), '2021-08-31 17:14:02.955403', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Rejected'), '2021-08-31 17:14:10.540992', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Pickup and Delivery'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Ready to Schedule'), '2021-08-31 17:14:44.698850', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Pickup and Delivery'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Pending'), '2021-08-31 17:14:47.619593', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Pickup and Delivery'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Ready to Verify'), '2021-08-31 17:14:50.838869', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Pickup and Delivery'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Complete'), '2021-08-31 17:15:21.920200', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Pickup and Delivery'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Not Complete - Other'), '2021-08-31 17:15:24.729662', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Pickup and Delivery'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Not Complete - No Show'), '2021-08-31 17:15:27.085621', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Signature'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Ready to Schedule'), '2021-08-31 17:20:00.589072', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Signature'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Pending'), '2021-08-31 17:20:04.082377', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Signature'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Ready to Verify'), '2021-08-31 17:20:07.222196', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Signature'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Complete'), '2021-08-31 17:20:11.562530', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Signature'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Not Complete - No Show'), '2021-08-31 17:20:14.872489', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Signature'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Not Complete - Other'), '2021-08-31 17:20:17.354200', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Complete'), '2021-08-31 17:04:51.490083', '2021-09-02 16:53:14.884038', 2356764, 2356764, true);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Not Complete - No Show'), '2021-08-31 17:05:51.805488', '2021-09-02 16:53:22.926065', 2356764, 2356764, true);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Not Complete - No Show'), '2021-09-02 16:53:27.224690', null, 2356764, null, false);
INSERT INTO flow.event_company_event_status_type (event_id, company_event_status_type_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Cancelled'), '2021-08-31 17:14:05.222916', '2021-09-02 16:53:35.992835', 2356764, 2356764, true);
-- process step events
INSERT INTO flow.process_step_event (process_step_id, event_id, initial_company_event_status_type_id, date_created, unique_behavior_type_id, display_order, date_modified, created_by_id, modified_by_id, archived) VALUES ((select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting'), (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Pickup and Delivery'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Ready to Schedule'), '2021-09-01 14:56:29.367645', null, 2, null, 2356764, null, false);
INSERT INTO flow.process_step_event (process_step_id, event_id, initial_company_event_status_type_id, date_created, unique_behavior_type_id, display_order, date_modified, created_by_id, modified_by_id, archived) VALUES ((select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting'), (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Signature'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Ready to Schedule'), '2021-09-01 14:56:35.134029', null, 3, null, 2356764, null, false);
INSERT INTO flow.process_step_event (process_step_id, event_id, initial_company_event_status_type_id, date_created, unique_behavior_type_id, display_order, date_modified, created_by_id, modified_by_id, archived) VALUES ((select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting'), (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Ready to Submit'), '2021-09-01 14:56:19.442835', null, 1, '2021-09-02 16:40:44.377198', 2356764, 2356764, false);
INSERT INTO flow.process_step_event (process_step_id, event_id, initial_company_event_status_type_id, date_created, unique_behavior_type_id, display_order, date_modified, created_by_id, modified_by_id, archived) VALUES ((select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting'), (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'), (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Ready to Schedule'), '2021-09-01 14:56:12.571947', null, 0, '2021-09-02 16:52:56.782129', 2356764, 2356764, false);
-- process step event actions
INSERT INTO flow.process_step_event_action (process_step_event_id, display_order, company_event_status_type_id, company_process_step_status_type_id, require_start_time, require_end_time, require_resource, always_enabled, multiple_uses, action_name, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission')), 0, (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Pending'), (select id from flow.company_process_step_status_type where company_id = 3 and process_step_status_type = 'Pending In-Person Permit Submission'), true, true, true, true, false, 'Scheduled', false, '2021-09-01 15:41:28.352760', '2021-09-02 16:26:50.552767', 2356764, 2356764);
INSERT INTO flow.process_step_event_action (process_step_event_id, display_order, company_event_status_type_id, company_process_step_status_type_id, require_start_time, require_end_time, require_resource, always_enabled, multiple_uses, action_name, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission')), 1, (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Pending Approval'), (select id from flow.company_process_step_status_type where company_id = 3 and process_step_status_type = 'Pending Permit Approval'), true, true, true, true, false, 'Submission Verified', false, '2021-09-02 16:27:40.472236', '2021-09-02 16:30:21.502519', 2356764, 2356764);
INSERT INTO flow.process_step_event_action (process_step_event_id, display_order, company_event_status_type_id, company_process_step_status_type_id, require_start_time, require_end_time, require_resource, always_enabled, multiple_uses, action_name, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission')), 2, (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Approved'), (select id from flow.company_process_step_status_type where company_id = 3 and process_step_status_type = 'Disposition Permit Approval'), true, true, true, true, false, 'Approved', false, '2021-09-02 16:32:04.883736', '2021-09-02 16:35:47.321102', 2356764, 2356764);
INSERT INTO flow.process_step_event_action (process_step_event_id, display_order, company_event_status_type_id, company_process_step_status_type_id, require_start_time, require_end_time, require_resource, always_enabled, multiple_uses, action_name, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission')), 3, (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Rejected'), (select id from flow.company_process_step_status_type where company_id = 3 and process_step_status_type = 'Disposition Permit Rejection'), true, true, true, true, false, 'Rejected', false, '2021-09-02 16:39:14.595558', '2021-09-02 16:40:02.375724', 2356764, 2356764);
INSERT INTO flow.process_step_event_action (process_step_event_id, display_order, company_event_status_type_id, company_process_step_status_type_id, require_start_time, require_end_time, require_resource, always_enabled, multiple_uses, action_name, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission')), 0, (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Pending Approval'), (select id from flow.company_process_step_status_type where company_id = 3 and process_step_status_type = 'Pending Permit Approval'), true, false, true, false, false, 'Submitted A', false, '2021-09-02 16:41:51.805762', '2021-09-02 16:43:10.188507', 2356764, 2356764);
INSERT INTO flow.process_step_event_action (process_step_event_id, display_order, company_event_status_type_id, company_process_step_status_type_id, require_start_time, require_end_time, require_resource, always_enabled, multiple_uses, action_name, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission')), 1, (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Pending Approval'), null, true, false, true, false, false, 'Submitted B', false, '2021-09-02 16:42:02.091420', '2021-09-02 16:43:13.861885', 2356764, 2356764);
INSERT INTO flow.process_step_event_action (process_step_event_id, display_order, company_event_status_type_id, company_process_step_status_type_id, require_start_time, require_end_time, require_resource, always_enabled, multiple_uses, action_name, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission')), 2, (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Approved'), (select id from flow.company_process_step_status_type where company_id = 3 and process_step_status_type = 'Disposition Permit Approval'), true, false, true, true, false, 'Approved', false, '2021-09-02 16:44:21.741432', '2021-09-02 16:45:14.141019', 2356764, 2356764);
INSERT INTO flow.process_step_event_action (process_step_event_id, display_order, company_event_status_type_id, company_process_step_status_type_id, require_start_time, require_end_time, require_resource, always_enabled, multiple_uses, action_name, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission')), 3, (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Rejected'), (select id from flow.company_process_step_status_type where company_id = 3 and process_step_status_type = 'Disposition Permit Rejection'), true, false, true, true, false, 'Rejected', false, '2021-09-02 16:44:31.987288', '2021-09-02 16:45:19.480637', 2356764, 2356764);
INSERT INTO flow.process_step_event_action (process_step_event_id, display_order, company_event_status_type_id, company_process_step_status_type_id, require_start_time, require_end_time, require_resource, always_enabled, multiple_uses, action_name, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Pickup and Delivery')), 0, (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Pending'), (select id from flow.company_process_step_status_type where company_id = 3 and process_step_status_type = 'Pending Permit Pickup and Delivery'), true, true, true, false, false, 'Scheduled', false, '2021-09-02 19:25:26.520326', '2021-09-02 19:30:49.845818', 2356764, 2356764);
INSERT INTO flow.process_step_event_action (process_step_event_id, display_order, company_event_status_type_id, company_process_step_status_type_id, require_start_time, require_end_time, require_resource, always_enabled, multiple_uses, action_name, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Pickup and Delivery')), 1, (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Complete'), (select id from flow.company_process_step_status_type where company_id = 3 and process_step_status_type = 'Permit(s) Approved and Delivered'), true, true, true, false, false, 'Delivery Verified', false, '2021-09-02 19:28:47.404486', '2021-09-02 19:30:56.548064', 2356764, 2356764);
INSERT INTO flow.process_step_event_action (process_step_event_id, display_order, company_event_status_type_id, company_process_step_status_type_id, require_start_time, require_end_time, require_resource, always_enabled, multiple_uses, action_name, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Signature')), 0, (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Pending'), (select id from flow.company_process_step_status_type where company_id = 3 and process_step_status_type = 'Pending Permit Signature'), true, true, true, false, false, 'Scheduled', false, '2021-09-02 19:31:41.143278', '2021-09-02 19:33:38.504060', 2356764, 2356764);
INSERT INTO flow.process_step_event_action (process_step_event_id, display_order, company_event_status_type_id, company_process_step_status_type_id, require_start_time, require_end_time, require_resource, always_enabled, multiple_uses, action_name, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Signature')), 1, (select id from flow.company_event_status_type where company_id = 3 and event_status_type = 'Complete'), (select id from flow.company_process_step_status_type where company_id = 3 and process_step_status_type = 'Ready to Submit Permit(s)'), true, true, true, false, false, 'Permit Signature Verified', false, '2021-09-02 19:33:34.947652', '2021-09-03 15:58:52.517359', 2356764, 2356764);
-- process step event action field
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Approved' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'))),         (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'Permit Decision Verified By') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'))), true, false, '2021-09-02 16:32:44.132117', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Approved' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'))),         (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'Permit Submission Event Outcome') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'))), true, false, '2021-09-02 16:32:44.995809', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Approved' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'))),         (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'AHJ') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'))), true, false, '2021-09-02 16:32:45.330446', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Approved' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'))),         (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'Permit type') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'))), true, false, '2021-09-02 16:32:45.669249', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Approved' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'))),         (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'Permit Submission Scheduled By') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'))), true, false, '2021-09-02 16:32:46.116691', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Rejected' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'))),         (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'Permit Decision Verified By') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'))), true, false, '2021-09-02 16:39:55.090528', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Rejected' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'))),         (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'Permit Decision') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'))), true, false, '2021-09-02 16:39:55.095776', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Rejected' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'))),         (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'Permit Submission Event Outcome') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'))), true, false, '2021-09-02 16:39:55.600806', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Rejected' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'))),         (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'AHJ') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'))), true, false, '2021-09-02 16:39:55.910951', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Rejected' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'))),         (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'Permit Type') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'))), true, false, '2021-09-02 16:39:56.495560', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Rejected' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'))),         (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'Permit Submission Scheduled By') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - In Person Permit Submission'))), true, false, '2021-09-02 16:39:56.848103', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Submitted A' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))),         (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'Permit Type') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))), true, false, '2021-09-02 16:43:06.565543', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Submitted A' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))),         (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'AHJ') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))), true, false, '2021-09-02 16:43:07.309128', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Submitted B' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))),         (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'Permit Type') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))), true, false, '2021-09-02 16:43:12.549530', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Submitted B' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))),         (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'AHJ') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))), true, false, '2021-09-02 16:43:12.928532', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Approved' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))),            (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'Permit Type') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))), true, false, '2021-09-02 16:45:11.438184', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Approved' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))),            (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'AHJ') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))), true, false, '2021-09-02 16:45:11.688969', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Approved' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))),            (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'Permit Decision') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))), true, false, '2021-09-02 16:45:12.064034', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Approved' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))),            (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'Permit Decision Verified By') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))), true, false, '2021-09-02 16:45:12.481614', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Rejected' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))),            (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'Permit Type') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))), true, false, '2021-09-02 16:45:17.721974', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Rejected' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))),            (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'AHJ') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))), true, false, '2021-09-02 16:45:18.117057', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Rejected' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))),            (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'Permit Decision') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))), true, false, '2021-09-02 16:45:18.460584', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Rejected' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))),            (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'Permit Decision Verified By') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))), true, false, '2021-09-02 16:45:18.740630', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Scheduled' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Pickup and Delivery'))),         (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'Permit Pickup Scheduled By') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Pickup and Delivery'))), true, false, '2021-09-02 19:30:48.416840', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Delivery Verified' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Pickup and Delivery'))), (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'Permit Pickup and Delivery Event Outcome') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Pickup and Delivery'))), true, false, '2021-09-02 19:30:53.672037', null, null, null);
INSERT INTO flow.process_step_event_action_field (process_step_event_action_id, custom_field_group_assignment_id, required, archived, date_created, date_modified, created_by_id, modified_by_id)
  VALUES ((select id from flow.process_step_event_action where action_name = 'Delivery Verified' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Pickup and Delivery'))), (select id from flow.custom_field_group_assignment where custom_field_id = (select id from flow.custom_field where company_id = 3 and field_name = 'Permit Pickup Scheduled By') and custom_field_group_id = (select id from flow.custom_field_group where group_name = 'Permit Details' and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Pickup and Delivery'))), true, false, '2021-09-02 19:30:53.784827', null, null, null);
-- process step event requirement - with process step event logic
with pser as (
  INSERT INTO flow.process_step_event_requirement (process_step_requirement_type_id, process_step_event_id, operator_type_id, requirement_value, data_type_requirement_id, secondary_requirement_value, custom_field_group_assignment_id, company_function_id, requirement_nbr, date_created, date_modified, created_by_id, modified_by_id, archived, list_of_value_id, list_of_value_ids, immutable, system_list_option_id, custom_sql_option_id, migrated_company_id, migrated_original_id, reference_process_step_id)
  VALUES (7, (select id from flow.process_step_event where event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission') and process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting')), 5, null, null, null, null, null, 1, '2021-09-02 16:41:34.519010', null, 2356764, null, false, null, '{1062}', true, null, null, null, null, (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting'))
  returning id
), psel_1 as (
  INSERT INTO flow.process_step_event_logic (process_step_event_requirement_id, operation_type_id, sql_order, process_step_event_action_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from pser), null, 1, (select id from flow.process_step_event_action where action_name = 'Submitted A' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))), '2021-09-02 16:42:40.518644', null, 2356764, null, false)
)
INSERT INTO flow.process_step_event_logic (process_step_event_requirement_id, operation_type_id, sql_order, process_step_event_action_id, date_created, date_modified, created_by_id, modified_by_id, archived)
VALUES ((select id from pser), null, 0, (select id from flow.process_step_event_action where action_name = 'Submitted B' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Online Permit Submission'))), '2021-09-02 16:42:46.871541', null, 2356764, null, false);
--next pser - with process step event logic
with pser as (
  INSERT INTO flow.process_step_event_requirement (process_step_requirement_type_id, process_step_event_id, operator_type_id, requirement_value, data_type_requirement_id, secondary_requirement_value, custom_field_group_assignment_id, company_function_id, requirement_nbr, date_created, date_modified, created_by_id, modified_by_id, archived, list_of_value_id, list_of_value_ids, immutable, system_list_option_id, custom_sql_option_id, migrated_company_id, migrated_original_id, reference_process_step_id)
  VALUES (1, (select id from flow.process_step_event where event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Pickup and Delivery') and process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting')), 2, null, 4, null, 21266, null, 1, '2021-09-02 19:29:04.658839', null, 2356764, null, false, null, '', true, null, null, null, null, null)
  returning id
), psel_1 as (
  INSERT INTO flow.process_step_event_logic (process_step_event_requirement_id, operation_type_id, sql_order, process_step_event_action_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from pser), null, 0, (select id from flow.process_step_event_action where action_name = 'Delivery Verified' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Pickup and Delivery'))), '2021-09-02 19:29:09.211762', '2021-09-02 19:29:33.814260', 2356764, 2356764, true)
), psel_ as (
  INSERT INTO flow.process_step_event_logic (process_step_event_requirement_id, operation_type_id, sql_order, process_step_event_action_id, date_created, date_modified, created_by_id, modified_by_id, archived)
  VALUES ((select id from pser), null, 0, (select id from flow.process_step_event_action where action_name = 'Scheduled' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Pickup and Delivery'))), '2021-09-02 19:29:26.371753', null, 2356764, null, false)
)
INSERT INTO flow.process_step_event_logic (process_step_event_requirement_id, operation_type_id, sql_order, process_step_event_action_id, date_created, date_modified, created_by_id, modified_by_id, archived)
VALUES ((select id from pser), null, 0, (select id from flow.process_step_event_action where action_name = 'Delivery Verified' and process_step_event_id = (select id from flow.process_step_event where process_step_id = (select id from flow.process_step where company_id = 3 and process_step_name = 'Permitting') and event_id = (select id from flow.event where company_id = 3 and event_name = 'DO NOT TOUCH - Permit Pickup and Delivery'))), '2021-09-02 19:29:33.817290', null, 2356764, null, false);
