-- INSERT 7 OAKS DEVS
INSERT INTO flow."user" (id, first_name, last_name, email, password, phone_number, created_by_id, date_created, modified_by_id, date_modified, default_company_id, username, archived)
    (select 99999998,'Mandy', 'Cosper', 'scott.humes@7oaksgroup.com', '$2a$10$gNj8M3uetkKFuYCMq6XXn.qeP4IeXwkzZTq3tUWQ1sLeop4bBEk92', null, null, now(), null, now(), 3, 'scott.humes@7oaksgroup.com', false where not exists (select id from flow."user" where username = 'scott.humes@7oaksgroup.com'));
INSERT INTO flow."user" (id, first_name, last_name, email, password, phone_number, created_by_id, date_created, modified_by_id, date_modified, default_company_id, username, archived)
    (select 99999997,'Joseph', 'Canto', 'joseph@7oaksgroup.com', '$2a$10$gNj8M3uetkKFuYCMq6XXn.qeP4IeXwkzZTq3tUWQ1sLeop4bBEk92', null, null, now(), null, now(), 3, 'joseph@7oaksgroup.com', false where not exists (select id from flow."user" where username = 'joseph@7oaksgroup.com'));
INSERT INTO flow."user" (id, first_name, last_name, email, password, phone_number, created_by_id, date_created, modified_by_id, date_modified, default_company_id, username, archived)
    (select 99999996,'Scott', 'Keller', 'kellersk@7oaksgroup.com', '$2a$10$vSjw76YpVDj3SYR1S10/D.6OFYHEzgDXOg8oWuJRbp1BuvmgER90.', null, null, now(), null, now(), 3, 'kellersk@7oaksgroup.com', false where not exists (select id from flow."user" where username = 'kellersk@7oaksgroup.com'));
INSERT INTO flow."user" (id, first_name, last_name, email, password, phone_number, created_by_id, date_created, modified_by_id, date_modified, default_company_id, username, archived)
    (select 99999995,'Mandy', 'Cosper', 'mandy@7oaksgroup.com', '$2a$10$.Yt8nujpN2q795POxbXiOuL.hJXhb7yzSo2bgYh7gRtcJWiWa5HKC', null, null, now(), null, now(), 3, 'mandy@7oaksgroup.com', false where not exists (select id from flow."user" where username = 'mandy@7oaksgroup.com'));
INSERT INTO flow."user" (id, first_name, last_name, email, password, phone_number, created_by_id, date_created, modified_by_id, date_modified, default_company_id, username, archived)
    (select 99999994,'Rick', 'Sanchez', 'scott.humes+rick@7oaksgroup.com', '$2a$10$GfvMhjU0nITML7KGWhLw9utbk5dT8qX1Nb6Q6b0qZ13f.DpPk0wMC', null, null, now(), null, now(), 3, 'scott.humes+rick@7oaksgroup.com', false where not exists (select id from flow."user" where username = 'scott.humes+rick@7oaksgroup.com'));
INSERT INTO flow."user" (id, first_name, last_name, email, password, phone_number, created_by_id, date_created, modified_by_id, date_modified, default_company_id, username, archived)
    (select 99999993,'John', 'Berns', 'john@7oaksgroup.com', '$2a$10$MVMAyDXJyX4G.AAL5C.mFetbuZtDhcduV/FIzVnp03AGYmjN9Woma', null, null, now(), null, now(), 3, 'john@7oaksgroup.com', false where not exists (select id from flow."user" where username = 'john@7oaksgroup.com'));
INSERT INTO flow."user" (id, first_name, last_name, email, password, phone_number, created_by_id, date_created, modified_by_id, date_modified, default_company_id, username, archived)
    (select 99999992,'Kory', 'Calmes', 'kory@calmes.org', '$2a$10$MVMAyDXJyX4G.AAL5C.mFetbuZtDhcduV/FIzVnp03AGYmjN9Woma', null, null, now(), null, now(), 3, 'kory@calmes.org', false where not exists (select id from flow."user" where username = 'kory@calmes.org'));
INSERT INTO flow."user" (id, first_name, last_name, email, password, phone_number, created_by_id, date_created, modified_by_id, date_modified, default_company_id, username, archived)
    (select 99999991,'Michael', 'Meyers', 'michael.meyers@xomly.com', '$2a$10$MVMAyDXJyX4G.AAL5C.mFetbuZtDhcduV/FIzVnp03AGYmjN9Woma', null, null, now(), null, now(), 3, 'michael.meyers@xomly.com', false where not exists (select id from flow."user" where username = 'michael.meyers@xomly.com'));
INSERT INTO flow."user" (id, first_name, last_name, email, password, phone_number, created_by_id, date_created, modified_by_id, date_modified, default_company_id, username, archived)
    (select 99999990,'Randa', 'Nunn', 'randa@randa.com', '$2a$10$MVMAyDXJyX4G.AAL5C.mFetbuZtDhcduV/FIzVnp03AGYmjN9Woma', null, null, now(), null, now(), 3, 'randa@randa.com', false where not exists (select id from flow."user" where username = 'randa@randa.com'));
INSERT INTO flow."user" (id, first_name, last_name, email, password, phone_number, created_by_id, date_created, modified_by_id, date_modified, default_company_id, username, archived)
  (select 69696969,'SYSTEM', 'SYSTEM', 'system@7oaksgroup.com', null, null, null, now(), null, now(), null, 'system@7oaksgroup.com', false where not exists (select id from flow."user" where username = 'system@7oaksgroup.com'));

-- ADD 7 OAKS DEVS TO ALBATROSS COMPANY
-- insert into flow.user_company(company_id, is_default, user_id)
--     (select 1, true, (select id from flow."user" where username = 'scott.humes@7oaksgroup.com') where not exists (select id from flow.user_company where company_id = 1 and user_id = (select id from flow."user" where username = 'scott.humes@7oaksgroup.com')) );
insert into flow.user_company(company_id, is_default, user_id)
    (select 1, true, (select id from flow."user" where username = 'joseph@7oaksgroup.com') where not exists (select id from flow.user_company where company_id = 1 and user_id = (select id from flow."user" where username = 'joseph@7oaksgroup.com')) );
insert into flow.user_company(company_id, is_default, user_id)
    (select 1, true, (select id from flow."user" where username = 'kellersk@7oaksgroup.com') where not exists (select id from flow.user_company where company_id = 1 and user_id = (select id from flow."user" where username = 'kellersk@7oaksgroup.com')) );
insert into flow.user_company(company_id, is_default, user_id)
    (select 1, true, (select id from flow."user" where username = 'mandy@7oaksgroup.com') where not exists (select id from flow.user_company where company_id = 1 and user_id = (select id from flow."user" where username = 'mandy@7oaksgroup.com')) );
insert into flow.user_company(company_id, is_default, user_id)
    (select 1, true, (select id from flow."user" where username = 'scott.humes+rick@7oaksgroup.com') where not exists (select id from flow.user_company where company_id = 1 and user_id = (select id from flow."user" where username = 'scott.humes+rick@7oaksgroup.com')) );
insert into flow.user_company(company_id, is_default, user_id)
    (select 1, true, (select id from flow."user" where username = 'john@7oaksgroup.com') where not exists (select id from flow.user_company where company_id = 1 and user_id = (select id from flow."user" where username = 'john@7oaksgroup.com')) );
insert into flow.user_company(company_id, is_default, user_id)
    (select 1, true, (select id from flow."user" where username = 'kory@calmes.org') where not exists (select id from flow.user_company where company_id = 1 and user_id = (select id from flow."user" where username = 'kory@calmes.org')) );
insert into flow.user_company(company_id, is_default, user_id)
    (select 1, true, (select id from flow."user" where username = 'michael.meyers@xomly.com') where not exists (select id from flow.user_company where company_id = 1 and user_id = (select id from flow."user" where username = 'michael.meyers@xomly.com')) );
insert into flow.user_company(company_id, is_default, user_id)
    (select 1, true, (select id from flow."user" where username = 'randa@randa.com') where not exists (select id from flow.user_company where company_id = 1 and user_id = (select id from flow."user" where username = 'randa@randa.com')) );

-- ADD TEST CUSTOM FIELDS FOR MOBILE
-- create list of value parents (for mobile testing)
INSERT INTO flow.list_of_value (name, code, parent_id, display_order, date_created, date_modified, created_by_id, modified_by_id, archived) VALUES ('Kory Dropdown Field', null, null, null, '2020-05-04 20:55:21.535159', null, 2350555, null, false);
INSERT INTO flow.list_of_value (name, code, parent_id, display_order, date_created, date_modified, created_by_id, modified_by_id, archived) VALUES ('Kory Multi-Select Field', null, null, null, '2020-05-04 20:55:46.034388', null, 2350555, null, false);

-- create list of values (for mobile testing)
INSERT INTO flow.list_of_value (name, code, parent_id, display_order, date_created, date_modified, created_by_id, modified_by_id, archived) VALUES ('Option 2', null, (select id from flow.list_of_value where name = 'Kory Dropdown Field'), 1, '2020-05-04 20:55:21.547846', null, 2350555, null, false);
INSERT INTO flow.list_of_value (name, code, parent_id, display_order, date_created, date_modified, created_by_id, modified_by_id, archived) VALUES ('Option 1', null, (select id from flow.list_of_value where name = 'Kory Dropdown Field'), 0, '2020-05-04 20:55:21.539886', null, 2350555, null, false);
INSERT INTO flow.list_of_value (name, code, parent_id, display_order, date_created, date_modified, created_by_id, modified_by_id, archived) VALUES ('Option 3', null, (select id from flow.list_of_value where name = 'Kory Multi-Select Field'), 2, '2020-05-04 20:55:46.039550', null, 2350555, null, false);
INSERT INTO flow.list_of_value (name, code, parent_id, display_order, date_created, date_modified, created_by_id, modified_by_id, archived) VALUES ('Option 2', null, (select id from flow.list_of_value where name = 'Kory Multi-Select Field'), 1, '2020-05-04 20:55:46.038073', null, 2350555, null, false);
INSERT INTO flow.list_of_value (name, code, parent_id, display_order, date_created, date_modified, created_by_id, modified_by_id, archived) VALUES ('Option 1', null, (select id from flow.list_of_value where name = 'Kory Multi-Select Field'), 0, '2020-05-04 20:55:46.036518', null, 2350555, null, false);

-- create the custom fields (for mobile testing)
INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key) VALUES (null, 3, 'Kory Text Field', 1, '2020-05-04 20:54:00.046517', null, 2350555, null, false, null, '{null}', null, null);
INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key) VALUES (null, 3, 'Kory Date Field', 2, '2020-05-04 20:54:09.307443', null, 2350555, null, false, null, '{null}', null, null);
INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key) VALUES (null, 3, 'Kory Timestamp Field', 3, '2020-05-04 20:54:21.961026', null, 2350555, null, false, null, '{null}', null, null);
INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key) VALUES (null, 3, 'Kory Boolean Field', 4, '2020-05-04 20:54:31.011507', null, 2350555, null, false, null, '{null}', null, null);
INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key) VALUES (null, 3, 'Kory Integer Field', 5, '2020-05-04 20:54:50.982201', null, 2350555, null, false, null, '{null}', null, null);
INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key) VALUES (null, 3, 'Kory Decimal Field', 6, '2020-05-04 20:54:59.948875', null, 2350555, null, false, null, '{null}', null, null);
INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key) VALUES ((select id from flow.list_of_value where name = 'Kory Dropdown Field'), 3, 'Kory Dropdown Field', 7, '2020-05-04 20:55:21.552864', null, 2350555, null, false, null, '{null}', null, null);
INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key) VALUES ((select id from flow.list_of_value where name = 'Kory Multi-Select Field'), 3, 'Kory Multi-Select Field', 8, '2020-05-04 20:55:46.042339', null, 2350555, null, false, null, '{null}', null, null);
INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key) VALUES (null, 3, 'Kory System List Field', 10, '2020-05-04 20:56:29.037412', null, 2350555, null, false, 2, '{1}', null, null);
INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key) VALUES (null, 3, 'Kory System Field', 9, '2020-05-04 20:56:06.750352', null, 2350555, null, false, null, '{null}', 'brs.ahj', 'customFieldSql.brs.ahjList');

-- create custom field object type connection  (for mobile testing)
-- contacts (for mobile testing)
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Text Field'), 2, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Date Field'), 2, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Timestamp Field'), 2, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Boolean Field'), 2, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Integer Field'), 2, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Decimal Field'), 2, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Dropdown Field'), 2, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Multi-Select Field'), 2, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory System Field'), 2, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory System List Field'), 2, false, true);
-- projects (for mobile testing)
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Text Field'), 1, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Date Field'), 1, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Timestamp Field'), 1, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Boolean Field'), 1, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Integer Field'), 1, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Decimal Field'), 1, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Dropdown Field'), 1, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Multi-Select Field'), 1, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory System Field'), 1, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory System List Field'), 1, false, true);

-- CONTACTS (for mobile testing)
-- create custom field group (for mobile testing)
INSERT INTO flow.custom_field_group (group_name, company_object_type_id, group_order, archived, process_step_id, event_type_id,created_by_id,date_created) VALUES ('Kory Test Contact Group DONT DELETE PLEASE', 2, 0, true, null, null,2350555,now());

-- create custom field group assignment (for mobile testing)
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Contact Group DONT DELETE PLEASE'), 565, null, 0, false, '2020-05-04 20:56:50.619427', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Contact Group DONT DELETE PLEASE'), 563, null, 0, false, '2020-05-04 20:56:54.403526', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Contact Group DONT DELETE PLEASE'), 567, null, 0, false, '2020-05-04 20:56:57.011763', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Contact Group DONT DELETE PLEASE'), 568, null, 0, false, '2020-05-04 20:56:59.828196', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Contact Group DONT DELETE PLEASE'), 566, null, 0, false, '2020-05-04 20:57:02.402972', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Contact Group DONT DELETE PLEASE'), 569, null, 0, false, '2020-05-04 20:57:04.945620', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Contact Group DONT DELETE PLEASE'), 570, null, 0, false, '2020-05-04 20:57:07.234348', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Contact Group DONT DELETE PLEASE'), 571, null, 0, false, '2020-05-04 20:57:10.135958', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Contact Group DONT DELETE PLEASE'), 562, null, 0, false, '2020-05-04 20:57:12.401288', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Contact Group DONT DELETE PLEASE'), 564, null, 0, false, '2020-05-04 20:57:15.347502', null, 2350555, null, null);

-- PROJECTS (for mobile testing)
-- create custom field group (for mobile testing)
INSERT INTO flow.custom_field_group (group_name, company_object_type_id, group_order, archived, process_step_id, event_type_id,created_by_id,date_created) VALUES ('Kory Test Project Group DONT DELETE PLEASE', 1, 0, true, null, null,2350555,now());

-- create custom field group assignment (for mobile testing)
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Project Group DONT DELETE PLEASE'), 565, null, 0, false, '2020-05-04 20:56:50.619427', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Project Group DONT DELETE PLEASE'), 563, null, 0, false, '2020-05-04 20:56:54.403526', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Project Group DONT DELETE PLEASE'), 567, null, 0, false, '2020-05-04 20:56:57.011763', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Project Group DONT DELETE PLEASE'), 568, null, 0, false, '2020-05-04 20:56:59.828196', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Project Group DONT DELETE PLEASE'), 566, null, 0, false, '2020-05-04 20:57:02.402972', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Project Group DONT DELETE PLEASE'), 569, null, 0, false, '2020-05-04 20:57:04.945620', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Project Group DONT DELETE PLEASE'), 570, null, 0, false, '2020-05-04 20:57:07.234348', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Project Group DONT DELETE PLEASE'), 571, null, 0, false, '2020-05-04 20:57:10.135958', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Project Group DONT DELETE PLEASE'), 562, null, 0, false, '2020-05-04 20:57:12.401288', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Project Group DONT DELETE PLEASE'), 564, null, 0, false, '2020-05-04 20:57:15.347502', null, 2350555, null, null);

INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@prod-0.1.0-337.plist', 'application/octet-stream', null, null, false, '2020-11-12 23:27:32.449350', null, false, 'blueraven/apps/ios/com.myblueraven.albatross/0.1.0/Albatross@prod-0.1.0-337.plist');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@prod-0.1.0-338.apk', 'application/vnd.android.package-archive', null, null, false, '2020-11-12 23:51:41.387503', null, false, 'blueraven/app/android/com.myblueraven.albatross/0.1.0/Albatross@prod-0.1.0-338.apk');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@prod-0.1.0-337.plist', 'application/octet-stream', null, null, false, '2020-11-12 23:27:32.449350', null, false, 'blueraven/apps/ios/com.myblueraven.albatross/0.1.0/Albatross@prod-0.1.0-337.plist');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@prod-0.1.0-338.apk', 'application/vnd.android.package-archive', null, null, false, '2020-11-12 23:51:41.387503', null, false, 'blueraven/app/android/com.myblueraven.albatross/0.1.0/Albatross@prod-0.1.0-338.apk');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-271.plist', 'application/octet-stream', null, null, false, '2020-10-28 17:51:33.280250', null, false, 'blueraven/apps/ios/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-271.plist');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-272.apk', 'application/vnd.android.package-archive', null, null, false, '2020-10-28 18:19:06.830545', null, false, 'blueraven/app/android/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-272.apk');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-286.plist', 'application/octet-stream', null, null, false, '2020-10-29 23:54:13.604773', null, false, 'blueraven/apps/ios/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-286.plist');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-287.apk', 'application/vnd.android.package-archive', null, null, false, '2020-10-30 00:19:19.357726', null, false, 'blueraven/app/android/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-287.apk');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-289.plist', 'application/octet-stream', null, null, false, '2020-10-30 16:18:31.867717', null, false, 'blueraven/apps/ios/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-289.plist');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-290.apk', 'application/vnd.android.package-archive', null, null, false, '2020-10-30 16:44:36.945107', null, false, 'blueraven/app/android/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-290.apk');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-293.apk', 'application/vnd.android.package-archive', null, null, false, '2020-10-30 17:36:23.415590', null, false, 'blueraven/app/android/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-293.apk');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-295.plist', 'application/octet-stream', null, null, false, '2020-10-30 22:11:49.586112', null, false, 'blueraven/apps/ios/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-295.plist');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-296.apk', 'application/vnd.android.package-archive', null, null, false, '2020-10-30 22:36:27.377921', null, false, 'blueraven/app/android/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-296.apk');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-292.plist', 'application/octet-stream', null, null, false, '2020-10-30 17:10:22.153681', '2020-11-03 16:21:07.114015', false, 'blueraven/apps/ios/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-292.plist');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-284.apk', 'application/vnd.android.package-archive', null, null, false, '2020-10-29 20:59:18.644638', '2020-11-03 16:21:10.333835', false, 'blueraven/app/android/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-284.apk');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-269.apk', 'application/vnd.android.package-archive', null, null, false, '2020-10-27 16:02:15.587778', '2020-11-03 16:21:13.863606', false, 'blueraven/app/android/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-269.apk');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-268.plist', 'application/octet-stream', null, null, false, '2020-10-27 15:34:38.356619', '2020-11-03 16:21:16.179792', false, 'blueraven/apps/ios/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-268.plist');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-301.plist', 'application/octet-stream', null, null, false, '2020-11-03 01:16:33.836490', '2020-11-04 16:35:48.064642', false, 'blueraven/apps/ios/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-301.plist');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-283.plist', 'application/octet-stream', null, null, false, '2020-10-29 20:29:59.218821', '2020-11-04 16:35:51.154475', false, 'blueraven/apps/ios/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-283.plist');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-299.apk', 'application/vnd.android.package-archive', null, null, false, '2020-10-31 00:31:40.280072', '2020-11-04 16:35:59.649233', false, 'blueraven/app/android/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-299.apk');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-304.plist', 'application/octet-stream', null, null, false, '2020-11-04 00:43:49.784199', null, false, 'blueraven/apps/ios/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-304.plist');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-302.apk', 'application/vnd.android.package-archive', null, null, false, '2020-11-03 01:40:46.953284', '2020-11-04 16:35:57.104109', false, 'blueraven/app/android/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-302.apk');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-305.apk', 'application/vnd.android.package-archive', null, null, false, '2020-11-04 01:08:11.885008', null, false, 'blueraven/app/android/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-305.apk');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-298.plist', 'application/octet-stream', null, null, false, '2020-10-31 00:08:17.468855', '2020-11-04 16:35:45.617046', false, 'blueraven/apps/ios/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-298.plist');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-311.apk', 'application/vnd.android.package-archive', null, null, false, '2020-11-05 01:33:51.250785', '2020-11-05 15:25:43.894818', true, 'blueraven/app/android/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-311.apk');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-307.plist', 'application/octet-stream', null, null, false, '2020-11-04 01:32:49.030868', '2020-11-05 15:25:47.228317', false, 'blueraven/apps/ios/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-307.plist');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-310.plist', 'application/octet-stream', null, null, false, '2020-11-05 01:06:42.562797', '2020-11-05 15:31:17.575768', true, 'blueraven/apps/ios/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-310.plist');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-308.apk', 'application/vnd.android.package-archive', null, null, false, '2020-11-04 01:56:43.099873', '2020-11-05 15:31:20.296179', false, 'blueraven/app/android/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-308.apk');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-313.plist', 'application/octet-stream', null, null, false, '2020-11-05 19:32:14.706147', null, false, 'blueraven/apps/ios/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-313.plist');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-314.apk', 'application/vnd.android.package-archive', null, null, false, '2020-11-05 19:56:08.745378', null, false, 'blueraven/app/android/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-314.apk');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-316.plist', 'application/octet-stream', null, null, false, '2020-11-06 21:38:44.199775', null, false, 'blueraven/apps/ios/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-316.plist');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-317.apk', 'application/vnd.android.package-archive', null, null, false, '2020-11-06 22:03:47.385373', null, false, 'blueraven/app/android/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-317.apk');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-343.plist', 'application/octet-stream', null, null, false, '2020-11-16 21:24:17.312712', '2020-11-17 00:46:09.816448', false, 'blueraven/apps/ios/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-343.plist');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-344.apk', 'application/vnd.android.package-archive', null, null, false, '2020-11-16 21:49:35.349331', null, false, 'blueraven/app/android/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-344.apk');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-346.plist', 'application/octet-stream', null, null, false, '2020-11-17 00:13:10.783766', '2020-11-17 01:15:46.552503', false, 'blueraven/apps/ios/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-346.plist');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-349.plist', 'application/octet-stream', null, null, false, '2020-11-17 01:09:41.283666', '2020-11-17 02:04:14.356402', true, 'blueraven/apps/ios/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-349.plist');
INSERT INTO blueraven.attachment ( filename, content_type, old_s3_key, size, deleted, created, updated, show, s3_key) VALUES ( 'Albatross@uat-0.1.0-350.apk', 'application/vnd.android.package-archive', null, null, false, '2020-11-17 01:33:28.683125', '2020-11-17 01:36:31.769687', true, 'blueraven/app/android/com.myblueraven.albatross/0.1.0/Albatross@uat-0.1.0-350.apk');

INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184805, 1, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184806, 3, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184807, 1, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184808, 3, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184809, 2, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184810, 4, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184811, 2, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184812, 4, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184813, 2, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184814, 4, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184815,4, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184816,2, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184817, 4, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184818, 2, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184819, 4, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184820,4, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184821, 2, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184822, 2, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184823, 2, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184824, 4, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184825, 2, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184826, 4, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184827, 4, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184828, 2, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184829, 4, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184830, 2, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184831, 2, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184832, 4, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184833, 2, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184834, 4, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184835, 2, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184836, 4, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184837, 2, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184838, 4, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184839, 2, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184840, 2, 8);
INSERT INTO blueraven.attachment_source (attachment_id, source_id, attachment_source_type_id) VALUES (184841, 4, 8);


--
-- select * from blueraven.attachment
-- where filename like '%.plist%' or  filename like '%.apk%'
--     and deleted is false;
--
-- select * from  blueraven.attachment
-- where (filename like '%.plist%' or  filename like '%.apk%')
--   and deleted is false
--   and filename like '%Albatross%'
-- order by id;
--
-- select attachment_id,source_id,attachment_source_type_id from blueraven.attachment_source
-- where attachment_id in (select id from  blueraven.attachment
--                         where (filename like '%.plist%' or  filename like '%.apk%')
--                           and deleted is false
--                           and filename like '%Albatross%')
-- order by attachment_id;
