-- INSERT 7 OAKS DEVS
INSERT INTO flow."user" (first_name, last_name, email, password, phone_number, created_by_id, date_created, modified_by_id, date_modified, default_company_id, username, archived)
    (select 'Mandy', 'Cosper', 'scott.humes@7oaksgroup.com', '$2a$10$gNj8M3uetkKFuYCMq6XXn.qeP4IeXwkzZTq3tUWQ1sLeop4bBEk92', null, null, now(), null, now(), 3, 'scott.humes@7oaksgroup.com', false where not exists (select id from flow."user" where username = 'scott.humes@7oaksgroup.com'));
INSERT INTO flow."user" (first_name, last_name, email, password, phone_number, created_by_id, date_created, modified_by_id, date_modified, default_company_id, username, archived)
    (select 'Joseph', 'Canto', 'joseph@7oaksgroup.com', '$2a$10$gNj8M3uetkKFuYCMq6XXn.qeP4IeXwkzZTq3tUWQ1sLeop4bBEk92', null, null, now(), null, now(), 3, 'joseph@7oaksgroup.com', false where not exists (select id from flow."user" where username = 'joseph@7oaksgroup.com'));
INSERT INTO flow."user" (first_name, last_name, email, password, phone_number, created_by_id, date_created, modified_by_id, date_modified, default_company_id, username, archived)
    (select 'Scott', 'Keller', 'kellersk@7oaksgroup.com', '$2a$10$vSjw76YpVDj3SYR1S10/D.6OFYHEzgDXOg8oWuJRbp1BuvmgER90.', null, null, now(), null, now(), 3, 'kellersk@7oaksgroup.com', false where not exists (select id from flow."user" where username = 'kellersk@7oaksgroup.com'));
INSERT INTO flow."user" (first_name, last_name, email, password, phone_number, created_by_id, date_created, modified_by_id, date_modified, default_company_id, username, archived)
    (select 'Mandy', 'Cosper', 'mandy@7oaksgroup.com', '$2a$10$.Yt8nujpN2q795POxbXiOuL.hJXhb7yzSo2bgYh7gRtcJWiWa5HKC', null, null, now(), null, now(), 3, 'mandy@7oaksgroup.com', false where not exists (select id from flow."user" where username = 'mandy@7oaksgroup.com'));
INSERT INTO flow."user" (first_name, last_name, email, password, phone_number, created_by_id, date_created, modified_by_id, date_modified, default_company_id, username, archived)
    (select 'Rick', 'Sanchez', 'scott.humes+rick@7oaksgroup.com', '$2a$10$GfvMhjU0nITML7KGWhLw9utbk5dT8qX1Nb6Q6b0qZ13f.DpPk0wMC', null, null, now(), null, now(), 3, 'scott.humes+rick@7oaksgroup.com', false where not exists (select id from flow."user" where username = 'scott.humes+rick@7oaksgroup.com'));
INSERT INTO flow."user" (first_name, last_name, email, password, phone_number, created_by_id, date_created, modified_by_id, date_modified, default_company_id, username, archived)
    (select 'John', 'Berns', 'john@7oaksgroup.com', '$2a$10$MVMAyDXJyX4G.AAL5C.mFetbuZtDhcduV/FIzVnp03AGYmjN9Woma', null, null, now(), null, now(), 3, 'john@7oaksgroup.com', false where not exists (select id from flow."user" where username = 'john@7oaksgroup.com'));
INSERT INTO flow."user" (first_name, last_name, email, password, phone_number, created_by_id, date_created, modified_by_id, date_modified, default_company_id, username, archived)
    (select 'Kory', 'Calmes', 'kory@calmes.org', '$2a$10$MVMAyDXJyX4G.AAL5C.mFetbuZtDhcduV/FIzVnp03AGYmjN9Woma', null, null, now(), null, now(), 3, 'kory@calmes.org', false where not exists (select id from flow."user" where username = 'kory@calmes.org'));
INSERT INTO flow."user" (first_name, last_name, email, password, phone_number, created_by_id, date_created, modified_by_id, date_modified, default_company_id, username, archived)
    (select 'Michael', 'Meyers', 'michael.meyers@xomly.com', '$2a$10$MVMAyDXJyX4G.AAL5C.mFetbuZtDhcduV/FIzVnp03AGYmjN9Woma', null, null, now(), null, now(), 3, 'michael.meyers@xomly.com', false where not exists (select id from flow."user" where username = 'michael.meyers@xomly.com'));
INSERT INTO flow."user" (first_name, last_name, email, password, phone_number, created_by_id, date_created, modified_by_id, date_modified, default_company_id, username, archived)
    (select 'Randa', 'Nunn', 'randa@randa.com', '$2a$10$MVMAyDXJyX4G.AAL5C.mFetbuZtDhcduV/FIzVnp03AGYmjN9Woma', null, null, now(), null, now(), 3, 'randa@randa.com', false where not exists (select id from flow."user" where username = 'randa@randa.com'));

-- ADD 7 OAKS DEVS TO ALBATROSS COMPANY
-- insert into flow.user_company(company_id, is_default, user_id)
--     (select 1, true, (select id from flow."user" where username = 'scott.humes@7oaksgroup.com') where not exists (select id from flow.user_company where company_id = 1 and user_id = (select id from flow."user" where username = 'scott.humes@7oaksgroup.com')) );
insert into flow.user_company(company_id, is_default, user_id)
    (select 1, true, (select id from flow."user" where username = 'joseph@7oaksgroup.com') where not exists (select id from flow.user_company where company_id = 1 and user_id = (select id from flow."user" where username = 'joseph@7oaksgroup.com')) );
insert into flow.user_company(company_id, is_default, user_id)
    (select 1, true, (select id from flow."user" where username = 'kellersk@7oaksgroup.com') where not exists (select id from flow.user_company where company_id = 1 and user_id = (select id from flow."user" where username = 'kellersk@7oaksgroup.com')) );
insert into flow.user_company(company_id, is_default, user_id)
    (select 1, true, (select id from flow."user" where username = 'mandy@7oaksgroup.com') where not exists (select id from flow.user_company where company_id = 1 and user_id = (select id from flow."user" where username = 'mandy@7oaksgroup.com')) );
insert into flow.user_company(company_id, is_default, user_id)
    (select 1, true, (select id from flow."user" where username = 'scott.humes+rick@7oaksgroup.com') where not exists (select id from flow.user_company where company_id = 1 and user_id = (select id from flow."user" where username = 'scott.humes+rick@7oaksgroup.com')) );
insert into flow.user_company(company_id, is_default, user_id)
    (select 1, true, (select id from flow."user" where username = 'john@7oaksgroup.com') where not exists (select id from flow.user_company where company_id = 1 and user_id = (select id from flow."user" where username = 'john@7oaksgroup.com')) );
insert into flow.user_company(company_id, is_default, user_id)
    (select 1, true, (select id from flow."user" where username = 'kory@calmes.org') where not exists (select id from flow.user_company where company_id = 1 and user_id = (select id from flow."user" where username = 'kory@calmes.org')) );
insert into flow.user_company(company_id, is_default, user_id)
    (select 1, true, (select id from flow."user" where username = 'michael.meyers@xomly.com') where not exists (select id from flow.user_company where company_id = 1 and user_id = (select id from flow."user" where username = 'michael.meyers@xomly.com')) );
insert into flow.user_company(company_id, is_default, user_id)
    (select 1, true, (select id from flow."user" where username = 'randa@randa.com') where not exists (select id from flow.user_company where company_id = 1 and user_id = (select id from flow."user" where username = 'randa@randa.com')) );

-- ADD TEST CUSTOM FIELDS FOR MOBILE
-- create list of value parents (for mobile testing)
INSERT INTO flow.list_of_value (name, code, parent_id, display_order, date_created, date_modified, created_by_id, modified_by_id, archived) VALUES ('Kory Dropdown Field', null, null, null, '2020-05-04 20:55:21.535159', null, 2350555, null, false);
INSERT INTO flow.list_of_value (name, code, parent_id, display_order, date_created, date_modified, created_by_id, modified_by_id, archived) VALUES ('Kory Multi-Select Field', null, null, null, '2020-05-04 20:55:46.034388', null, 2350555, null, false);

-- create list of values (for mobile testing)
INSERT INTO flow.list_of_value (name, code, parent_id, display_order, date_created, date_modified, created_by_id, modified_by_id, archived) VALUES ('Option 2', null, (select id from flow.list_of_value where name = 'Kory Dropdown Field'), 1, '2020-05-04 20:55:21.547846', null, 2350555, null, false);
INSERT INTO flow.list_of_value (name, code, parent_id, display_order, date_created, date_modified, created_by_id, modified_by_id, archived) VALUES ('Option 1', null, (select id from flow.list_of_value where name = 'Kory Dropdown Field'), 0, '2020-05-04 20:55:21.539886', null, 2350555, null, false);
INSERT INTO flow.list_of_value (name, code, parent_id, display_order, date_created, date_modified, created_by_id, modified_by_id, archived) VALUES ('Option 3', null, (select id from flow.list_of_value where name = 'Kory Multi-Select Field'), 2, '2020-05-04 20:55:46.039550', null, 2350555, null, false);
INSERT INTO flow.list_of_value (name, code, parent_id, display_order, date_created, date_modified, created_by_id, modified_by_id, archived) VALUES ('Option 2', null, (select id from flow.list_of_value where name = 'Kory Multi-Select Field'), 1, '2020-05-04 20:55:46.038073', null, 2350555, null, false);
INSERT INTO flow.list_of_value (name, code, parent_id, display_order, date_created, date_modified, created_by_id, modified_by_id, archived) VALUES ('Option 1', null, (select id from flow.list_of_value where name = 'Kory Multi-Select Field'), 0, '2020-05-04 20:55:46.036518', null, 2350555, null, false);

-- create the custom fields (for mobile testing)
INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key) VALUES (null, 3, 'Kory Text Field', 1, '2020-05-04 20:54:00.046517', null, 2350555, null, false, null, '{null}', null, null);
INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key) VALUES (null, 3, 'Kory Date Field', 2, '2020-05-04 20:54:09.307443', null, 2350555, null, false, null, '{null}', null, null);
INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key) VALUES (null, 3, 'Kory Timestamp Field', 3, '2020-05-04 20:54:21.961026', null, 2350555, null, false, null, '{null}', null, null);
INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key) VALUES (null, 3, 'Kory Boolean Field', 4, '2020-05-04 20:54:31.011507', null, 2350555, null, false, null, '{null}', null, null);
INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key) VALUES (null, 3, 'Kory Integer Field', 5, '2020-05-04 20:54:50.982201', null, 2350555, null, false, null, '{null}', null, null);
INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key) VALUES (null, 3, 'Kory Decimal Field', 6, '2020-05-04 20:54:59.948875', null, 2350555, null, false, null, '{null}', null, null);
INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key) VALUES ((select id from flow.list_of_value where name = 'Kory Dropdown Field'), 3, 'Kory Dropdown Field', 7, '2020-05-04 20:55:21.552864', null, 2350555, null, false, null, '{null}', null, null);
INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key) VALUES ((select id from flow.list_of_value where name = 'Kory Multi-Select Field'), 3, 'Kory Multi-Select Field', 8, '2020-05-04 20:55:46.042339', null, 2350555, null, false, null, '{null}', null, null);
INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key) VALUES (null, 3, 'Kory System List Field', 10, '2020-05-04 20:56:29.037412', null, 2350555, null, false, 2, '{1}', null, null);
INSERT INTO flow.custom_field (list_of_value_id, company_id, field_name, company_data_type_id, date_created, date_modified, created_by_id, modified_by_id, archived, company_system_list_id, system_list_option_ids, custom_field_sql_reference_table, custom_field_sql_key) VALUES (null, 3, 'Kory System Field', 9, '2020-05-04 20:56:06.750352', null, 2350555, null, false, null, '{null}', 'brs.ahj', 'customFieldSql.brs.ahjList');

-- create custom field object type connection  (for mobile testing)
-- contacts (for mobile testing)
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Text Field'), 2, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Date Field'), 2, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Timestamp Field'), 2, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Boolean Field'), 2, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Integer Field'), 2, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Decimal Field'), 2, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Dropdown Field'), 2, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Multi-Select Field'), 2, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory System Field'), 2, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory System List Field'), 2, false, true);
-- projects (for mobile testing)
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Text Field'), 1, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Date Field'), 1, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Timestamp Field'), 1, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Boolean Field'), 1, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Integer Field'), 1, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Decimal Field'), 1, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Dropdown Field'), 1, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory Multi-Select Field'), 1, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory System Field'), 1, false, true);
INSERT INTO flow.custom_field_object_type (custom_field_id, company_object_type_id, archived, show_on_insert) VALUES ((select id from flow.custom_field where field_name = 'Kory System List Field'), 1, false, true);

-- CONTACTS (for mobile testing)
-- create custom field group (for mobile testing)
INSERT INTO flow.custom_field_group (group_name, company_object_type_id, group_order, archived, process_step_id, event_type_id) VALUES ('Kory Test Contact Group DONT DELETE PLEASE', 2, 0, true, null, null);

-- create custom field group assignment (for mobile testing)
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Contact Group DONT DELETE PLEASE'), 565, null, 0, false, '2020-05-04 20:56:50.619427', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Contact Group DONT DELETE PLEASE'), 563, null, 0, false, '2020-05-04 20:56:54.403526', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Contact Group DONT DELETE PLEASE'), 567, null, 0, false, '2020-05-04 20:56:57.011763', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Contact Group DONT DELETE PLEASE'), 568, null, 0, false, '2020-05-04 20:56:59.828196', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Contact Group DONT DELETE PLEASE'), 566, null, 0, false, '2020-05-04 20:57:02.402972', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Contact Group DONT DELETE PLEASE'), 569, null, 0, false, '2020-05-04 20:57:04.945620', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Contact Group DONT DELETE PLEASE'), 570, null, 0, false, '2020-05-04 20:57:07.234348', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Contact Group DONT DELETE PLEASE'), 571, null, 0, false, '2020-05-04 20:57:10.135958', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Contact Group DONT DELETE PLEASE'), 562, null, 0, false, '2020-05-04 20:57:12.401288', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Contact Group DONT DELETE PLEASE'), 564, null, 0, false, '2020-05-04 20:57:15.347502', null, 2350555, null, null);

-- PROJECTS (for mobile testing)
-- create custom field group (for mobile testing)
INSERT INTO flow.custom_field_group (group_name, company_object_type_id, group_order, archived, process_step_id, event_type_id) VALUES ('Kory Test Project Group DONT DELETE PLEASE', 1, 0, true, null, null);

-- create custom field group assignment (for mobile testing)
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Project Group DONT DELETE PLEASE'), 565, null, 0, false, '2020-05-04 20:56:50.619427', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Project Group DONT DELETE PLEASE'), 563, null, 0, false, '2020-05-04 20:56:54.403526', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Project Group DONT DELETE PLEASE'), 567, null, 0, false, '2020-05-04 20:56:57.011763', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Project Group DONT DELETE PLEASE'), 568, null, 0, false, '2020-05-04 20:56:59.828196', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Project Group DONT DELETE PLEASE'), 566, null, 0, false, '2020-05-04 20:57:02.402972', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Project Group DONT DELETE PLEASE'), 569, null, 0, false, '2020-05-04 20:57:04.945620', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Project Group DONT DELETE PLEASE'), 570, null, 0, false, '2020-05-04 20:57:07.234348', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Project Group DONT DELETE PLEASE'), 571, null, 0, false, '2020-05-04 20:57:10.135958', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Project Group DONT DELETE PLEASE'), 562, null, 0, false, '2020-05-04 20:57:12.401288', null, 2350555, null, null);
INSERT INTO flow.custom_field_group_assignment (custom_field_group_id, custom_field_id, ancillary_custom_field_group_assignment_id, field_order, archived, date_created, date_modified, created_by_id, modified_by_id, schedule_field_type_id) VALUES ((select id from flow.custom_field_group where group_name = 'Kory Test Project Group DONT DELETE PLEASE'), 564, null, 0, false, '2020-05-04 20:57:15.347502', null, 2350555, null, null);


;


