application.name        = Albatross
application.description = Albatross for Blueraven

app.goodleap.api.host   = ${GOODLEAP_API_HOST:host}
app.goodleap.api.key    = ${GOODLEAP_API_KEY:key}

app.scheduled.enabled   = ${SCHEDULED_ENABLED:false}

#any company specific cron configs handled here
app.scheduled.blueraven.enabled                     = ${SCHEDULED_BLUERAVEN_ENABLED:false}
app.cron.blueraven.processGenesysContacts.enabled   = ${PROCESS_GENESYS_CONTACTS_ENABLED:false}

app.cron.sendSms.enabled                    = ${CRON_SENDSMS_ENABLED:false}
app.cron.cacheAvailability.enabled          = ${CRON_CACHE_AVAILABILITY_ENABLED:false}
app.cron.processFutureAppointments.enabled  = ${CRON_PROCESS_FUTURE_APPOINTMENTS_ENABLED:false}
app.cron.autoTriggers.enabled               = ${CRON_AUTOTRIGGERS_ENABLED:false}
app.cron.initialAutoTriggers.enabled        = ${CRON_INITIAL_AUTOTRIGGERS_ENABLED:false}
app.installAgreement.processing.enabled     = ${INSTALL_AGREEMENT_PROCESSING_ENABLED:false}
app.cron.fillProjectGeoCoords.enabled       = false
app.home_url                                = ${HOME_URL:http://localhost:8080}
app.host                                    = ${HOST_URL:http://localhost:8080}

app.html-to-pdf-api     = http://localhost:1323/api/convert
app.image-proxy.enabled = ${APP_IMAGE_PROXY_ENABLED:false}
app.image-proxy.url     = http://localhost:9090
app.image-proxy.key     = 6e655533cc43eb87d579e526ee3a9d8dff4a62fcb8639333aacc0f76844ef84a
app.image-proxy.salt    = e79df0c71fea1e4f59c0a21175eccb5532673de726926e0d3807f0b6416d6835

aws.accessKeyId     = ${AWS_ACCESS_KEY:test}
aws.secretKey       = ${AWS_SECRET:test}
aws.storageBucket   = ${AWS_BUCKET:blueraven-local}
#local only with localstack
aws.serviceEndpoint  = ${AWS_SERVICE_ENDPOINT:http://localhost:4566}

aurora.api.tenantId  = ${AURORA_TENANT:test}
aurora.api.token     = ${AURORA_TOKEN:test}

birdeye.api.key                 = ${BIRDEYE_KEY:}
birdeye.api.toplevelBusinessId  = ${BIRDEYE_TOPLEVEL_BUSINESS_ID:}
birdeye.api.sendInvitesForReal  = ${BIRDEYE_SEND_INVITES_FOR_REAL:false}
birdeye.api.serverDomain        = ${BIRDEYE_SERVER_DOMAIN:DEVO}
birdeye.api.surveyId            = 29921
birdeye.api.surveyGroupId       = 7606

spring.flyway.baseline-on-migrate   = true
spring.flyway.baseline-version = 0

genesys.api.client.id       =
genesys.api.client.secret   =

management.endpoints.web.exposure.include   = info,health,metrics,prometheus,loggers,startup

mapbox.token        = ${MAPBOX_TOKEN:}
mapbox.tilesetId    = ${MAPBOX_TILESET_ID:blueraven-dev.3qndkb5s}

pandadoc.api.access_token       = ${PANDADOC_TOKEN:pandadoc}
pandadoc.api.document.prefix    = ${PANDADOC_DOCUMENT_PREFIX:blueraven}

server.shutdown                 = immediate
server.error.include-stacktrace = never
server.error.include-message    = always

spring.lifecycle.timeout-per-shutdown-phase = 15s

spring.datasource.url           = ${DATABASE_URL:jdbc:postgresql://localhost:5433/blueraven}
spring.datasource.readonly.url  = ${DATABASE_READONLY_URL:jdbc:postgresql://localhost:5433/blueraven}
spring.datasource.username      = ${DATABASE_USERNAME:dbadmin}
spring.datasource.password      = ${DATABASE_PASSWORD:password}

spring.datasource.hikari.data-source-properties.rewriteBatchedInserts   = true

spring.servlet.multipart.maxFileSize    = 1000MB
spring.servlet.multipart.maxRequestSize = 1000MB

spring.task.execution.pool.core-size    = 5
spring.task.execution.pool.max-size     = 10
spring.task.execution.thread-name-prefix= AlbaExecutor

#spring redis
spring.data.redis.repositories.enabled  = false
spring.redis.client-type                = lettuce
spring.redis.host                       = ${REDIS_HOST:localhost}
spring.redis.password                   = ${REDIS_PASSWORD:}
spring.redis.port                       = ${REDIS_PORT:6379}
spring.redis.database                   = 0

security.jwt.phrase                     = ${JWT_PHRASE:supercalifragilisticexpialidocious}
security.jwt.expireDuration             = 7
security.jwt.masqueradeExpireDuration   = 30
security.doCompanyDefaultValidation     = false

springdoc.swagger-ui.enabled    = true

smtp.server     = ${SMTP_SERVER:localhost}
smtp.port       = ${SMTP_PORT:1025}
smtp.user       = ${SMTP_USER:}
smtp.password   = ${SMTP_PASSWORD:}
smtp.rateLimit  = 10

sunlight.api.token      = ${SUNLIGHT_API_TOKEN:}
sunlight.api.username   = ${SUNLIGHT_API_USERNAME:}
sunlight.api.password   = ${SUNLIGHT_API_PASSWORD:}
sunlight.api.host       = ${SUNLIGHT_API_HOST:}
sunlight.api.portal     = ${SUNLIGHT_API_PORTAL:}

#sunpower
sunpower.api.token  = ${SUNPOWER_TOKEN:sunpower}
sunpower.api.host   = ${SUNPOWER_HOST:http://sunpower}

#Squeeze
squeeze.api.host    = ${SQUEEZE_API_HOST:}

#Verse
verse.api.key    = ${VERSE_KEY:test}

#twilio
twilio.phoneNumber                  = ${TWILIO_NUMBER:}
twilio.accountSID                   = ${TWILIO_ACCOUNT:}
twilio.authToken                    = ${TWILIO_TOKEN:}
twilio.customersMessageServiceSID   = ${TWILIO_CUSTOMER_MESSAGE_SID:}


#Helpful loggers
#logging.level.org.springframework.jdbc.core = TRACE
#logging.level.com.albatross.api.v1.company.blueraven.controllers.proposal = DEBUG
#logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss,America/Denver}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} [%8.15t] %clr(%-40.40logger{0}){blue} %clr(:){blue} %clr(%m){faint}%n
#logging.level.com.albatross.api=INFO
#logging.level.com.twilio=DEBUG
