application.name=Albatross
application.description=Albatross for Blueraven
app.scheduled.enabled=${scheduled.enabled:false}
#any company specific cron configs handled here
app.scheduled.blueraven.enabled=${scheduled.blueraven.enabled:false}
app.cron.blueraven.processFive9Contacts.enabled=${cron.blueraven.processFive9Contacts.enabled:false}
app.cron.blueraven.processGenesysContacts.enabled=${cron.blueraven.processGenesysContacts.enabled:false}
app.cron.blueraven.processGetTheReferralContacts.enabled=${cron.blueraven.processGetTheReferralContacts.enabled:false}
app.cron.blueraven.processKlaviyoContacts.enabled=${cron.blueraven.processKlaviyoContacts.enabled:false}
app.cron.blueraven.processMetroPostalCodes.enabled=${cron.blueraven.processMetroPostalCodes.enabled:false}
app.cron.blueraven.processWebhookFinancialFields.enabled=${cron.blueraven.processWebhookFinancialFields.enabled:false}
app.cron.blueraven.marketo.enabled=${cron.blueraven.marketo.enabled:false}
app.cron.sendSms.enabled=${cron.sendSms.enabled:false}
app.cron.sendEmail.enabled=${cron.sendEmail.enabled:false}
app.cron.sendPushNotifications.enabled=${cron.sendPushNotifications.enabled:false}
app.cron.cacheAvailability.enabled=${cron.cacheAvailability.enabled:false}
app.cron.processFutureAppointments.enabled=${cron.processFutureAppointments.enabled:false}
app.cron.autoTriggers.enabled=${cron.autoTriggers.enabled:false}
app.cron.initialAutoTriggers.enabled=${cron.initialAutoTriggers.enabled:false}
app.installAgreement.processing.enabled=${installAgreement.processing.enabled:false}
app.cron.fillProjectGeoCoords.enabled=${cron.fillProjectGeoCoords.enabled:false}
app.cron.closeProjectConversations.enabled=${cron.closeProjectConversations.enabled:false}
app.cron.closeUserConversations.enabled=${cron.closeUserConversations.enabled:false}
app.cron.runDataViewMaintenance.enabled=${cron.runDataViewMaintenance.enabled:false}
app.cron.orgStructureRefresh.enabled=${cron.orgStructureRefresh.enabled:false}
app.home_url=${homeUrl}
app.host=${hostUrl}
app.html-to-pdf-api=${htmlToPdfUrl:http://localhost:4000}
app.env=${environment:null}
app.maintenanceMode=${maintenanceMode:false}
app.image-proxy.enabled=${imageProxy.enabled:false}
app.image-proxy.url=${imageProxy.url}
app.image-proxy.key=${imageProxy.key}
app.image-proxy.salt=${imageProxy.salt}
app.portal.url=${app.portalUrl}

##without this the max pageable request size is defaulted to 2000
spring.data.web.pageable.max-page-size=3000

server.shutdown=graceful
server.http2.enabled=true
# dont return trace in error response
server.error.include-stacktrace=never
server.error.include-message=always
server.forward-headers-strategy=native
server.compression.enabled=true
server.tomcat.remoteip.remote-ip-header=x-forwarded-for
spring.main.allow-circular-references=false
spring.lifecycle.timeout-per-shutdown-phase=15s
spring.cloud.httpclientfactories.ok.enabled=false
spring.datasource.url=${database.url}
spring.datasource.readonly.url=${database.readonly.url}
spring.datasource.username=${database.username}
spring.datasource.password=${database.password}
spring.datasource.name=HikariPool-Main
spring.flyway.enabled=true
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}
spring.flyway.ignore-migration-patterns=*:missing
spring.servlet.multipart.maxFileSize=1000MB
spring.servlet.multipart.maxRequestSize=1000MB
#spring.task.execution.pool.core-size=10
#spring.task.execution.pool.max-size=50
#spring.task.execution.pool.queue-capacity=50
spring.task.execution.thread-name-prefix=AlbaExecutor
spring.task.scheduling.thread-name-prefix=AlbaScheduler

#spring redis
spring.data.redis.repositories.enabled=false
spring.data.redis.client-type=lettuce
spring.data.redis.host=${redis.host}
spring.data.redis.password=${redis.password:}
spring.data.redis.port=${redis.port}
spring.data.redis.database=${redis.database:0}

spring.threads.virtual.enabled=false
#TODO: fix one spring cloud supports 3.2.x
spring.cloud.compatibility-verifier.enabled=false

#logging
logging.pattern.dateformat=yyyy-MM-dd HH:mm:ss,America/Denver
#logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss,America/Denver}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} [%8.15t] %clr(%-40.40logger{0}){blue} %clr(:){blue} %clr(%m){faint}%n
logging.level.com.albatross.api=${app.api.loglevel:INFO}
management.endpoints.web.exposure.include=info,health,metrics,prometheus,loggers
management.metrics.web.client.max-uri-tags=1000
management.metrics.web.server.max-uri-tags=1000
security.jwt.phrase=${jwt.phrase}
security.jwt.expireDuration=7
security.jwt.masqueradeExpireDuration=30
security.doCompanyDefaultValidation=${security.companyDefault.validation}
aws.accessKeyId=${aws.accessKey}
aws.secretKey=${aws.secret}
aws.storageBucket=${aws.bucket}
aws.token=${aws.token}
mapbox.token=${mapbox.token}
mapbox.tilesetId=${mapbox.tilesetId}
aurora.api.tenantId=${aurora.tenant}
aurora.api.token=${aurora.token}
aurora.api.host=${aurora.host:test}
aurora.api.tokenV2022=${aurora.tokenV2022:test}
verse.api.key=${verse.key}
solargraf.api.token=${solargraf.token}
solargraf.api.host=${solargraf.host:test}

#SWAGGER
springdoc.swagger-ui.enabled=${swagger.enabled:false}
wellsfargo.address.br.name=Blue Raven Solar
wellsfargo.address.br.street1=1220 S 630 E
wellsfargo.address.br.street2=Suit #430
wellsfargo.address.br.city=American Fork
wellsfargo.address.br.state=UT
wellsfargo.address.br.postalCode=84003
wellsfargo.address.bank.name=Wells Fargo
wellsfargo.address.bank.street1=501 N Main Street
wellsfargo.address.bank.city=Phoenix
wellsfargo.address.bank.state=AZ
wellsfargo.address.bank.postalCode=85254
pandadoc.api.enabled=${pandadoc.enabled:false}
pandadoc.api.access_token=${pandadoc.token}
pandadoc.api.document.prefix=${pandadoc.document.prefix}
pandadoc.api.notification.email=${pandadoc.notification.email:support@blueravensolar.com}
pandadoc.api.notification.enabled=${pandadoc.notification.enabled:false}
pandadoc.api.document.delay=${pandadoc.document.delay:30000}
pandadoc.api.notification.delay=${pandadoc.notification.delay:5000}
pandadoc.api.role.customer=${pandadoc.role.customer:Customer}
pandadoc.api.role.closer=${pandadoc.role.closer:Sales Representative}
pandadoc.api.role.support=${pandadoc.role.support:Blue Raven Solar}
pandadoc.api.genericName=${pandadoc.genericName:Generic}
smtp.server=${smtp.server}
smtp.port=${smtp.port}
smtp.user=${smtp.user}
smtp.password=${smtp.password}
app.smtp.rateLimit=${smtp.rateLimit:300}
#twilio
twilio.phoneNumber=${twilio.number}
twilio.internalPhoneNumber=${twilio.internalNumber}
twilio.accountSID=${twilio.account}
twilio.authToken=${twilio.token}
twilio.customersMessageServiceSID=${twilio.customerMessageSID}
redis.host=${redis.host}
redis.port=${redis.port}
redis.password=
cloud.aws.stack.auto=false
cloud.aws.region.auto=false
cloud.aws.region.static=us-east-1
# https://docs.spring.io/spring-cloud-aws/docs/2.2.3.RELEASE/reference/html/#amazon-sdk-configuration
logging.level.com.amazonaws.util.EC2MetadataUtils=error
birdeye.api.key=${birdeye.key}
birdeye.api.toplevelBusinessId=${birdeye.toplevelBusinessId}
birdeye.api.sendInvitesForReal=${birdeye.sendInvitesForReal:false}
birdeye.api.serverDomain=${birdeye.serverDomain:DEVO}
birdeye.api.fallbackBusinessId  = ${birdeye.fallbackBusinessId}

#bitrise
bitrise.api.key=${bitrise.key}
bitrise.api.slug=${bitrise.slug}

#goodleap
app.goodleap.api.host=${goodleap.api.host}
app.goodleap.api.key=${goodleap.api.key}
app.goodleap.newLoanUrl=${goodleap.newLoanUrl:https://sandbox01-apply.goodleap.com/solar/blueraven/}

#sunpower
sunpower.api.token=${sunpower.token}
sunpower.api.host=${sunpower.host}
sunpower.api.spfUrl=${sunpower.spfUrl:https://qa.financial.sunpower.com/new-application/loan}

#EnFin
enfin.api.host=${enfin.host:''}
enfin.api.clientId=${enfin.clientId:''}
enfin.api.secret=${enfin.secret:''}
enfin.api.username=${enfin.username:''}
enfin.api.password=${enfin.password:''}

#Mosaic
mosaic.api.host=${mosaic.host:''}
mosaic.api.clientId=${mosaic.clientId:''}
mosaic.api.secret=${mosaic.secret:''}

#Squeeze
squeeze.api.host=${squeeze.host}

#Five9
five9.api.token=${five9.token:''}

#GetTheReferral
getthereferral.api.token=${getthereferral.token:''}
getthereferral.api.host=${getthereferral.host:''}

#Klaviyo
klaviyo.api.token=${klaviyo.token:''}
klaviyo.api.host=${klaviyo.host:''}

#marketo
app.marketo.host=${marketo.host:}
app.marketo.clientId=${marketo.clientId:}
app.marketo.secret=${marketo.secret:}

#stripe - used for BR only
stripe.api.token=${stripe.token:''}
stripe.down.payment.product.key=${stripe.downPayment.productKey:''}

# these are used by 3rd party when a customer commits to get an installation done
breeze.stripe.api.token=${breeze.stripe.token:''}
breeze.stripe.down.payment.price.key=${breeze.stripe.downPayment.priceKey:''}
breeze.portal.host.url=${breeze.portal.hostUrl:''}


#firebase
app.firebase.credentials=${firebase.credentials:false}
app.firebase.dry-run=${app.firebase.dryRun:false}

# IL SREC (greenhouse, energy solutions)
app.srec.token=${srec.token:''}
app.srec.host=${srec.host:https://greenhouse-onboard.energy-solution.net/ilabp/v2}
