DROP FUNCTION IF EXISTS brs.process_permit_pack_log_history() cascade;
CREATE OR REPLACE FUNCTION brs.process_permit_pack_log_history() RETURNS trigger
  LANGUAGE plpgsql
AS
$$
BEGIN

  INSERT INTO brs.permit_pack_log_history(project_id,
                                          permit_pack_log_id,
                                          permit_pack_log_nbr,
                                          design_log_id,
                                          design_nbr,
                                          permit_pack_date,
                                          number_of_modules_mp1,
                                          number_of_modules_mp2,
                                          number_of_modules_mp3,
                                          number_of_modules_mp4,
                                          number_of_modules_mp5,
                                          number_of_modules_mp6,
                                          number_of_modules_mp7,
                                          number_of_modules_mp8,
                                          azimuth_mp1,
                                          azimuth_mp2,
                                          azimuth_mp3,
                                          azimuth_mp4,
                                          azimuth_mp5,
                                          azimuth_mp6,
                                          azimuth_mp7,
                                          azimuth_mp8,
                                          pitch_mp1,
                                          pitch_mp2,
                                          pitch_mp3,
                                          pitch_mp4,
                                          pitch_mp5,
                                          pitch_mp6,
                                          pitch_mp7,
                                          pitch_mp8,
                                          tsrf_mp1,
                                          tsrf_mp2,
                                          tsrf_mp3,
                                          tsrf_mp4,
                                          tsrf_mp5,
                                          tsrf_mp6,
                                          tsrf_mp7,
                                          tsrf_mp8,
                                          mp1_roof_area,
                                          mp2_roof_area,
                                          mp3_roof_area,
                                          mp4_roof_area,
                                          mp5_roof_area,
                                          mp6_roof_area,
                                          mp7_roof_area,
                                          mp8_roof_area,
                                          panels_on_primary_structure,
                                          panels_on_detached_structure,
                                          aurora_url,
                                          dc_system_size_kw,
                                          total_annual_production,
                                          module,
                                          module_count,
                                          inverter,
                                          ahj,
                                          utility,
                                          roof_material,
                                          number_of_stories,
                                          pv_breaker_ocpd_rating,
                                          load_side_interconnection,
                                          interconnection,
                                          non_standard_interconnection,
                                          placard_required,
                                          reroof_required,
                                          blocking_required,
                                          trenching_required,
                                          overhead_span,
                                          exterior_conduit_required,
                                          primary_mounting_hardware,
                                          primary_attachment,
                                          ac_disconnect_required,
                                          utility_pv_meter_required,
                                          primary_landscape_attachment_spacing,
                                          primary_portrait_attachment_spacing,
                                          ac_disconnect_rating,
                                          ac_disconnect_type,
                                          sheathing_type,
                                          framing_type,
                                          sheathing_attachment_required,
                                          system_offset,
                                          net_metering_rate,
                                          primary_structure_roof_area,
                                          arrays_on_primary_structure,
                                          arrays_on_detached_structure,
                                          mixed_mounting_hardware,
                                          home_is_3_stories,
                                          conduit_type,
                                          module_part_number,
                                          interconnection_interior_exterior,
                                          interconnection_supply_side_load_side,
                                          interconnection_method,
                                          point_of_interconnection,
                                          non_standard_interconnection_items,
                                          bom,
                                          date_created)
  VALUES (new.project_id, new.id, new.permit_pack_log_nbr, new.design_log_id, new.design_nbr, new.permit_pack_date,
          new.design ->> 'Number of Modules_mp1',
          new.design ->> 'Number of Modules_mp2',
          new.design ->> 'Number of Modules_mp3',
          new.design ->> 'Number of Modules_mp4',
          new.design ->> 'Number of Modules_mp5',
          new.design ->> 'Number of Modules_mp6',
          new.design ->> 'Number of Modules_mp7',
          new.design ->> 'Number of Modules_mp8',
          new.design ->> 'Azimuth_mp1',
          new.design ->> 'Azimuth_mp2',
          new.design ->> 'Azimuth_mp3',
          new.design ->> 'Azimuth_mp4',
          new.design ->> 'Azimuth_mp5',
          new.design ->> 'Azimuth_mp6',
          new.design ->> 'Azimuth_mp7',
          new.design ->> 'Azimuth_mp8',
          new.design ->> 'Pitch_mp1',
          new.design ->> 'Pitch_mp2',
          new.design ->> 'Pitch_mp3',
          new.design ->> 'Pitch_mp4',
          new.design ->> 'Pitch_mp5',
          new.design ->> 'Pitch_mp6',
          new.design ->> 'Pitch_mp7',
          new.design ->> 'Pitch_mp8',
          new.design ->> 'TSRF_mp1',
          new.design ->> 'TSRF_mp2',
          new.design ->> 'TSRF_mp3',
          new.design ->> 'TSRF_mp4',
          new.design ->> 'TSRF_mp5',
          new.design ->> 'TSRF_mp6',
          new.design ->> 'TSRF_mp7',
          new.design ->> 'TSRF_mp8',
          new.design ->> 'MP1 Roof Area',
          new.design ->> 'MP2 Roof Area',
          new.design ->> 'MP3 Roof Area',
          new.design ->> 'MP4 Roof Area',
          new.design ->> 'MP5 Roof Area',
          new.design ->> 'MP6 Roof Area',
          new.design ->> 'MP7 Roof Area',
          new.design ->> 'MP8 Roof Area',
          new.design ->> 'Panels on Primary Structure',
          new.design ->> 'Panels on Detached Structure',
          new.design ->> 'Aurora URL',
          new.design ->> 'DC System Size (kW)',
          new.design ->> 'Total Annual Production',
          new.design ->> 'Module',
          new.design ->> 'Module Count',
          new.design ->> 'Inverter',
          new.design ->> 'AHJ',
          new.design ->> 'Utility',
          new.design ->> 'Roof Material',
          new.design ->> 'Number of Stories',
          new.design ->> 'PV Breaker / OCPD Rating',
          new.design ->> 'Load Side Interconnection',
          new.design ->> 'Interconnection',
          new.design ->> 'Non Standard Interconnection',
          new.design ->> 'Placard Required',
          new.design ->> 'Reroof Required',
          new.design ->> 'Blocking Required',
          new.design ->> 'Trenching Required',
          new.design ->> 'Overhead Span',
          new.design ->> 'Exterior Conduit Required',
          new.design ->> 'Primary Mounting Hardware',
          new.design ->> 'Primary Attachment',
          new.design ->> 'AC Disconnect Required',
          new.design ->> 'Utility PV Meter Required',
          new.design ->> 'Primary Landscape Attachment Spacing',
          new.design ->> 'Primary Portrait Attachment Spacing',
          new.design ->> 'AC Disconnect Rating',
          new.design ->> 'AC Disconnect Type',
          new.design ->> 'Sheathing Type',
          new.design ->> 'Framing Type',
          new.design ->> 'Sheathing Attachment Required',
          new.design ->> 'System Offset',
          new.design ->> 'Net Metering Rate',
          new.design ->> 'Primary Structure Roof Area',
          new.design ->> 'Arrays on Primary Structure',
          new.design ->> 'Arrays on Detached Structure',
          new.design ->> 'Mixed Mounting Hardware',
          new.design ->> 'Home is 3+ stories',
          new.design ->> 'Conduit Type',
          new.design ->> 'Module Part Number',
          new.design ->> 'Interconnection Interior/Exterior',
          new.design ->> 'Interconnection Supply Side/Load Side',
          new.design ->> 'Interconnection Method',
          new.design ->> 'Point of Interconnection',
          new.design ->> 'Non Standard Interconnection Items',
          new.bom,
          now());
  RETURN NEW;
END;
$$;


create or replace trigger brs_permit_pack_log_history
  after insert
  on brs.permit_pack_log
  for each row
execute procedure brs.process_permit_pack_log_history();
