drop function if exists brs.process_proposal_log_history();
  CREATE OR REPLACE FUNCTION brs.process_proposal_log_history()
  RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO brs.proposal_log_history (filename,
                                        project_id,
                                        fullname,
                                        address,
                                        city,
                                        state,
                                        zip,
                                        phone,
                                        email,
                                        loan_type,
                                        loan_term,
                                        interest_rate,
                                        optional_down_payment,
                                        number_of_leds,
                                        number_of_ecobees,
                                        cost_per_kwh_before_solar,
                                        cost_per_kwh_after_solar,
                                        bp_plus_promotion,
                                        velocity_marketing,
                                        military_discount,
                                        show_graph,
                                        year_1_kwh_output,
                                        panel_number,
                                        panel_wattage,
                                        system_size,
                                        panel,
                                        number_of_inverters,
                                        inverter_mfg,
                                        inverter_default_model,
                                        inverter_custom_getting,
                                        number_of_monitors,
                                        monitor,
                                        utility_name,
                                        rate_structure,
                                        total_yearly_usage_pre_solar,
                                        tile_roof_adder,
                                        hidden_conduit_adder,
                                        flat_roof_adder,
                                        upsize_inverter,
                                        extra_adder,
                                        option_3_adder,
                                        extra_promotion_cost,
                                        plane_1_number_of_panels,
                                        plane_1_tsrf,
                                        plane_2_number_of_panels,
                                        plane_2_tsrf,
                                        plane_3_number_of_panels,
                                        plane_3_tsrf,
                                        plane_4_number_of_panels,
                                        plane_4_tsrf,
                                        plane_5_number_of_panels,
                                        plane_5_tsrf,
                                        plane_6_number_of_panels,
                                        plane_6_tsrf,
                                        plane_7_number_of_panels,
                                        plane_7_tsrf,
                                        automatic_adder,
                                        automatic_adder_cost,
                                        tile_roof_adder_cost,
                                        three_kw_adder,
                                        three_kw_adder_cost,
                                        four_kw_adder,
                                        four_kw_adder_cost,
                                        upsize_inverter_adder_cost,
                                        panel_adder,
                                        panel_adder_cost,
                                        flat_roof_adder_cost,
                                        hidden_conduit_adder_cost,
                                        total_adder_costs,
                                        ee_cost_per_watt,
                                        funding_amount,
                                        loan_fundingw,
                                        loan_cost_to_customer,
                                        total_cost_to_customer,
                                        offset_percent,
                                        dealer_fee,
                                        utility_escalator,
                                        annual_degradation,
                                        home_appreciationw,
                                        funding_cap,
                                        production_factor,
                                        south_production,
                                        south_production_dollarw,
                                        eastwest_production,
                                        eastwest_production_dollarw,
                                        total_cost,
                                        down_payment_above_line_incentive,
                                        referral_promotion,
                                        loan_funding_amount,
                                        loan_amount,
                                        itc,
                                        state_tax_credit,
                                        customer_oop_itc_only_applied,
                                        customer_oop_all_rebates_applied,
                                        average_monthly_usage_before_solar,
                                        monthly_cost_today_before_solar,
                                        average_monthly_usage_after_solar,
                                        average_monthly_solar_production,
                                        monthly_solar_costs,
                                        average_monthly_leftover_utility_power_kwh,
                                        average_leftover_utility_rate,
                                        average_monthly_utility_cost_after_solar,
                                        average_monthly_power_cost_after_solar,
                                        total_monthly_savings,
                                        current_monthly_consumption,
                                        consumption_after_ee,
                                        kwh_savings_from_ee,
                                        percent_saving_from_ee,
                                        current_yearly_consumption,
                                        yearly_consumption_after_ee,
                                        total_added_home_value_estimate,
                                        twenty_five_year_cost_of_power_before_solar,
                                        twenty_five_energy_cost,
                                        lifetime_savings,
                                        twenty_five_year_remaining_utility_bill,
                                        twenty_five_year_production,
                                        thirty_five_year_production,
                                        thirty_five_year_solar_cost,
                                        thirty_five_year_solar_cost_per_kwh,
                                        thirty_five_year_utility_usage,
                                        thirty_five_year_cost_before_solar,
                                        thirty_five_year_cost_per_kw_before_solar,
                                        current_utility_oet_rebate_per_watt,
                                        current_max_oet_rebate,
                                        current_oet_rebate,
                                        max_or_tax_credit,
                                        current_or_tax_credit,
                                        choice_pf,
                                        choice_payment,
                                        month_eighteen_payment,
                                        eighteen_plus_payment,
                                        month_eighteen_payment_itc_only,
                                        eighteen_plus_payment_itc_only,
                                        month_eighteen_payment_all_incentives,
                                        nineteen_plus_payments_all_incentives,
                                        factor_ee_into_new_usage,
                                        date_created,
                                        promotion_eighteen_months_free,
                                        secondary_loan_amount,
                                        salal_primary_loan_monthly_payment,
                                        salal_prmiary_loan_total_payment,
                                        salal_primary_loan_finance_charge,
                                        salal_primary_loan_total_sales_price,
                                        salal_secondary_loan_monthly_payment,
                                        salal_secondary_loan_total_payments,
                                        salal_secondary_loan_finance_charge,
                                        lead_source,
                                        non_standard_work,
                                        proposal_date,
                                        proposal_nbr,
                                        source,
                                        proposal_log_id,
                                        non_standard_work_2,
                                        zip_code_zone,
                                        proposal_owner,
                                        non_standard_work_1,
                                        non_standard_work_1_cost,
                                        non_standard_work_2_cost,
                                        non_standard_work_3,
                                        non_standard_work_3_cost,
                                        extra_adders_dollar_per_watt,
                                        bp_plus_amount,
                                        project_owner,
                                        cost_per_watt_adder,
                                        eto_eligible_kw,
                                        nv_energy_system_size_for_rebate,
                                        above_line_item_type,
                                        state_incentive_type,
                                        gallons_of_gasoline,
                                        home_electricity_use_for_one_year,
                                        trees_growing_for_ten_years,
                                        tons_of_waste_sent_to_landfill,
                                        is_epc,
                                        epc_price,
                                        aurora_design_id,
                                        five_year_payoff,
                                        six_year_payoff,
                                        seven_year_payoff,
                                        eight_year_payoff,
                                        nine_year_payoff,
                                        ten_year_payoff,
                                        eleven_year_payoff,
                                        twelve_year_payoff,
                                        thirteen_year_payoff,
                                        fourteen_year_payoff,
                                        fifteen_year_payoff,
                                        twenty_year_payoff,
                                        monthly_cost_today_after_solar,
                                        monthly_cost_5_years_after_solar,
                                        monthly_cost_5_years_before_solar,
                                        twenty_five_year_cost_before_solar,
                                        twenty_five_year_savings_after_solar,
                                        monthly_payment_first_5_years_tax_to_loan,
                                        monthly_payment_first_5_years_tax_and_savings_to_loan,
                                        monthly_payment_6_to_24_years_tax_to_loan,
                                        monthly_payment_6_to_24_years_tax_and_savings_to_loan,
                                        monthly_payment_first_5_years_no_incentive,
                                        monthly_payment_6_to_24_years_no_incentive,
                                        smart_start_months_19_to_60_monthly_rebate,
                                        month_19_required_payment,
                                        month_0_to_18_loan_payment,
                                        month_0_to_18_net_payment,
                                        month_19_to_60_net_payment,
                                        month_60_plus_net_payment,
                                        total_ancillary_cost,
                                        loan_product,
                                        number_of_promotion_payments,
                                        promotion_payment_amount,
                                        proposal_tool_version,
                                        storage_brand,
                                        storage_size_kwh,
                                        financed_ancillary_cost_with_fees,
                                        financed_system_cost_with_fees,
                                        discount,
                                        manual_adjustment,
                                        total_promotion_amount,
                                        storage_cost_with_fees,
                                        site_survey_resource_type,
                                        site_survey_time_estimate,
                                        site_survey_items
  )
  VALUES (new.proposal->>'_filename',
    new.project_id,
    new.proposal->>'Full Name',
    new.proposal->>'Address',
    new.proposal->>'City',
    new.proposal->>'State',
    new.proposal->>'Zip',
    new.proposal->>'Phone',
    new.proposal->>'Email',
    new.proposal->>'Loan Type',
    new.proposal->>'Loan Term',
    new.proposal->>'Interest Rate',
    new.proposal->>'Optional Down Payment',
    new.proposal->>'Number of LEDs',
    new.proposal->>'Number of EcoBees',
    new.proposal->>'Cost per kWh Before Solar',
    new.proposal->>'Cost per kWh After Solar',
    new.proposal->>'BP+ Promotion',
    new.proposal->>'Velocity Marketing',
    new.proposal->>'Military Discount',
    new.proposal->>'Show Graph',
    new.proposal->>'Year 1 kWh Output',
    new.proposal->>'Panel Number',
    new.proposal->>'Panel Wattage',
    new.proposal->>'System Size (w)',
    new.proposal->>'Panel',
    new.proposal->>'Number of Inverters',
    new.proposal->>'Inverter MFG',
    new.proposal->>'Inverter Default Model',
    new.proposal->>'Inverter Customer Getting',
    new.proposal->>'Number of Monitors',
    new.proposal->>'Monitor',
    new.proposal->>'Utility Name',
    new.proposal->>'Rate structure',
    new.proposal->>'Total Yearly Usage (Pre-Solar)',
    new.proposal->>'Tile Roof Adder',
    new.proposal->>'Hidden Conduit Adder',
    new.proposal->>'Flat Roof Adder',
    new.proposal->>'Upsize Inverter',
    new.proposal->>'Extra Adder',
    new.proposal->>'Option 3 Adder',
    new.proposal->>'Extra Promotion Cost',
    new.proposal->>'Plane 1 Number of Panels',
    new.proposal->>'Plane 1 TSRF',
    new.proposal->>'Plane 2 Number of Panels',
    new.proposal->>'Plane 2 TSRF',
    new.proposal->>'Plane 3 Number of Panels',
    new.proposal->>'Plane 3 TSRF',
    new.proposal->>'Plane 4 Number of Panels',
    new.proposal->>'Plane 4 TSRF',
    new.proposal->>'Plane 5 Number of Panels',
    new.proposal->>'Plane 5 TSRF',
    new.proposal->>'Plane 6 Number of Panels',
    new.proposal->>'Plane 6 TSRF',
    new.proposal->>'Plane 7 Number of Panels',
    new.proposal->>'Plane 7 TSRF',
    new.proposal->>'Automatic Adder',
    new.proposal->>'Automatic Adder Cost',
    new.proposal->>'Tile Roof Adder Cost',
    new.proposal->>'<3kW Adder',
    new.proposal->>'<3kW Adder Cost',
    new.proposal->>'<4kW Adder',
    new.proposal->>'<4kW Adder Cost',
    new.proposal->>'Upsize Inverter Adder Cost',
    new.proposal->>'Panel Adder',
    new.proposal->>'Panel Adder Cost',
    new.proposal->>'Flat Roof Adder Cost',
    new.proposal->>'Hidden Conduit Adder Cost',
    new.proposal->>'Total Adder Costs',
    new.proposal->>'EE Cost per Watt',
    new.proposal->>'Funding Amount',
    new.proposal->>'Loan Fundingw',
    new.proposal->>'Loan Cost to Customer',
    new.proposal->>'Total Cost to Customer',
    new.proposal->>'Offset %',
    new.proposal->>'Dealer Fee',
    new.proposal->>'Utility Escalator',
    new.proposal->>'Annual Degradation',
    new.proposal->>'Home Appreciationw',
    new.proposal->>'Funding Cap',
    new.proposal->>'Production Factor',
    new.proposal->>'South Production',
    new.proposal->>'South Production $w',
    new.proposal->>'EastWest Production',
    new.proposal->>'EastWest Production $w',
    new.proposal->>'Total Cost',
    new.proposal->>'Down PaymentAbove Line Incentives',
    new.proposal->>'Referral Promotion',
    new.proposal->>'Loan Funding Amount',
    new.proposal->>'Loan Amount',
    new.proposal->>'ITC',
    new.proposal->>'State Tax Credit',
    new.proposal->>'Customer OOP ITC Only Applied',
    new.proposal->>'Customer OOP All Rebates Applied',
    new.proposal->>'Average Monthly Usage Before Solar',
    new.proposal->>'Monthly Cost Today Before Solar',
    new.proposal->>'Average Monthly Usage After Solar',
    new.proposal->>'Average Monthly Solar Production',
    new.proposal->>'Monthly Solar Cost',
    new.proposal->>'Average Monthly Leftover Utility Power (kWh)',
    new.proposal->>'Average Leftover Utility Rate',
    new.proposal->>'Average Monthly Utility Cost Afer Solar',
    new.proposal->>'Average Monthly Power Cost After Solar',
    new.proposal->>'Total Monthly Savings',
    new.proposal->>'Current Monthy Consumption',
    new.proposal->>'Consumption After EE',
    new.proposal->>'kWh Saving From EE',
    new.proposal->>'% Savings from EE',
    new.proposal->>'Current Yearly Consumption',
    new.proposal->>'Yearly Consumption After EE',
    new.proposal->>'Total Added Home Value Estimate',
    new.proposal->>'25 Year Cost of Power Before Solar',
    new.proposal->>'25 Year Energy Costs',
    new.proposal->>'Lifetime Saving',
    new.proposal->>'25 Year Remaining Utility Bill',
    new.proposal->>'25 Year Production',
    new.proposal->>'35 Year Production',
    new.proposal->>'35 Year Solar Cost',
    new.proposal->>'35 Year Solar Cost per kWh',
    new.proposal->>'35 Year Utility Usage',
    new.proposal->>'35 Year Cost Before Solar',
    new.proposal->>'35 Year Cost per kWh Before Solar',
    new.proposal->>'Current Utility OET Rebate per watt',
    new.proposal->>'Current Max OET Rebate',
    new.proposal->>'Current OET Rebate',
    new.proposal->>'Max OR Tax Creadit',
    new.proposal->>'Current OR Tax Credit',
    new.proposal->>'Choice PF',
    new.proposal->>'Choice Payment',
    new.proposal->>'Month 18 Payment (No Month 18)',
    new.proposal->>'18+ Payment (No Month 18)',
    new.proposal->>'Month 18 Payment (ITC Only)',
    new.proposal->>'18+ Payment (ITC Only)',
    new.proposal->>'Month 18 Payment (All Incentives)',
    new.proposal->>'19+ Payment All Incentives',
    new.proposal->>'Factor EE into new usage?',
    now(),
    new.proposal->>'Promotion 18 Months Free',
    new.proposal->>'Secondary Loan Amount',
    new.proposal->>'(Salal) Primary Loan Monthly Payment',
    new.proposal->>'(Salal) Primary Loan Total of Payments',
    new.proposal->>'(Salal) Primary Loan Finance Charge',
    new.proposal->>'(Salal) Primary Loan Total Sale Price',
    new.proposal->>'(Salal) Secondary Loan Monthly Payment',
    new.proposal->>'(Salal) Secondary Loan Total of Payments',
    new.proposal->>'(Salal) Secondary Loan Finance Charge',
    new.proposal->>'Lead Source',
    new.proposal->>'Non-Standard Work',
    new.proposal_date,
    new.proposal_nbr,
    new.source,
    new.id,
    new.proposal->>'Non-Standard Work 2',
    new.proposal->>'Zip code zone',
    new.proposal->>'Proposal Owner',
    new.proposal->>'Non-Standard Work 1',
    new.proposal->>'Non-Standard Work 1 Cost',
    new.proposal->>'Non-Standard Work 2 Cost',
    new.proposal->>'Non-Standard Work 3',
    new.proposal->>'Non-Standard Work 3 Cost',
    new.proposal->>'Extra Adders ($w)',
    new.proposal->>'BP+ Amount',
    new.proposal->>'Deal Owner Name',
    new.proposal->>'$/W Adder',
    new.proposal->>'ETO Eligible kW',
    new.proposal->>'NV Energy System Size for Rebate',
    new.proposal->>'Above Line Item Type',
    new.proposal->>'State Incentive Type',
    new.proposal->>'Gallons of gasoline',
    new.proposal->>'Home electricity use for one year',
    new.proposal->>'Trees growing for 10 years',
    new.proposal->>'Tons of waste sent to landfill',
    new.proposal->>'EPC YN',
    new.proposal->>'EPC Price',
    new.proposal->>'Aurora Design ID',
    new.proposal->>'5 Year Payoff',
    new.proposal->>'6 Year Payoff',
    new.proposal->>'7 Year Payoff',
    new.proposal->>'8 Year Payoff',
    new.proposal->>'9 Year Payoff',
    new.proposal->>'10 Year Payoff',
    new.proposal->>'11 Year Payoff',
    new.proposal->>'12 Year Payoff',
    new.proposal->>'13 Year Payoff',
    new.proposal->>'14 Year Payoff',
    new.proposal->>'15 Year Payoff',
    new.proposal->>'20 Year Payoff',
    new.proposal->>'Monthly Cost Today After Solar',
    new.proposal->>'Monthly Cost 5 Years After Solar',
    new.proposal->>'Monthly Cost 5 Years Before Solar',
    new.proposal->>'25 Year Cost Before Solar',
    new.proposal->>'25 Year Savings After Solar',
    new.proposal->>'Monthly Payment First 5 Years Tax To Loan',
    new.proposal->>'Monthly Payment First 5 Years Tax And Savings To Loan',
    new.proposal->>'Monthly Payment 6 To 24 Years Tax To Loan',
    new.proposal->>'Monthly Payment 6 To 24 Years Tax And Savings To Loan',
    new.proposal->>'Monthly Payment First 5 Years No Incentive',
    new.proposal->>'Monthly Payment 6 To 24 Years No Incentive',
    new.proposal->>'Smart Start Months 19 To 60 Monthly Rebate',
    new.proposal->>'Month 19 Required Payment',
    new.proposal->>'Month 0 To 18 Loan Payment',
    new.proposal->>'Month 0 To 18 Net Payment',
    new.proposal->>'Month 19 To 60 Net Payment',
    new.proposal->>'Month 60 Plus Net Payment',
    new.proposal->>'Total Ancillary Cost',
    new.proposal->>'Loan Product',
    new.proposal->>'Number of Promotion Payments',
    new.proposal->>'Promotion Payment Amount',
    new.proposal->>'Proposal Tool Version',
    new.proposal->>'Storage Brand',
    new.proposal->>'Storage Size (kWh)',
    new.proposal->>'Financed Ancillary Cost With Fees',
    new.proposal->>'Financed System Cost With Fees',
    new.proposal->>'Discount',
    new.proposal->>'Manual Adjustment',
    new.proposal->>'Total Promotion Amount',
    new.proposal->>'Storage Cost With Fees',
    new.proposal->>'Site Survey Resource Type',
    new.proposal->>'Site Survey Time Estimate',
    new.proposal->>'Site Survey Items'
         );
  RETURN NEW;
END;
$$;

drop trigger if exists process_proposal_log_history on brs.proposal_log;
create trigger process_proposal_log_history
    after insert
    on brs.proposal_log
    for each row
execute procedure brs.process_proposal_log_history();
