package com.albatross.api.v1.company.blueraven.models;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class MarketoProject {

  private Long companyProjectStatusTypeId;

  private String projectId,
                 projectStatusType,
                 firstName,
                 lastName,
                 address,
                 city,
                 state,
                 country,
                 postalCode,
                 phone,
                 email,
                 leadStatus,
                 leadSource,
                 finalDesignApprovedDate,
                 energizedDate,
                 installationStartTime,
                 closerAppointmentStartTime,
                 inspectionStartTime,
                 substantialCompletionDate,
                 inspectionPassedDate,
                 completeDateBooking,
                 finalDesignSentToHomeownerDate,
                 permitPackSubmittalStartTime,
                 permitApprovedDate,
                 hoaApprovalNeededName,
                 hoaRequestForApprovalSubmittedDate,
                 hoaApprovalReceivedDate,
                 acCompressorRelocationRequired,
                 acCompressorRelocationStartTime,
                 acCompressorRelocationVerifiedDate,
                 mainPanelUpgradeRequiredInHouse,
                 inHouseMpuStartTime,
                 inHouseMpuVerifiedDate,
                 mainPanelUpgradeRequiredOutsourceName,
                 outsourceMpuStartTime,
                 outsourceMpuVerifiedDate,
                 reroofRequiredName,
                 reroofStartTime,
                 reroofVerifiedDate,
                 structuralUpgradeRequiredName,
                 structuralUpgradeStartTime,
                 structuralUpgradeVerifiedDate,
                 treeTrimRequiredName,
                 treeTrimmingStartTime,
                 treeTrimmingVerifiedDate,
                 trenchingRequiredName,
                 trenchingStartTime,
                 trenchingVerifiedDate,
                 interconnectionApplicationSignedDate,
                 interconnectionApplicationSubmittedToUtilityDate,
                 interconnectionApplicationApprovedDate,
                 installationReadyToScheduleDate,
                 ahjInspectionScheduledDate,
                 ahjInspectionApprovalSubmittedToUtilityDate,
                 utilityMeterSetDate,
                 utilityMeterOrderedDate,
                 siteSurveyScheduledDate,
                 finalDesignCreatedTimestamp,
                 finalDesignSignedDate,
                 finalDesignCompleteDate,
                 ahjFinalInspectionVerified,
                 ptoVerified,
                 readyToSendInstallationReminderEmail,
                 readyToSendFirstPermitUpdateEmail,
                 readyToSendSecondPermitUpdateEmail,
                 readyToSendThirdPermitUpdateEmail,
                 estimatedAhjApprovalTimeline,
                 leadSourceDetailName;

  private Boolean doNotSolicitReview;
}
