-- new smartlist system lists
INSERT INTO flow.smartlist_system_list (id, smartlist_system_list, archived) VALUES (4, 'Process Step Category', false);
INSERT INTO flow.smartlist_system_list (id, smartlist_system_list, archived) VALUES (5, 'Project Stage', false);

--project stage smartlist field
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (1, 'Project Stage', 'flow.project_status_type', 'project_status_type', 2350555, 1, 'flow.company_project_status_type', 'project_status_type_id', 5);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (51, 'Project Stage', 'flow.project_status_type', 'project_status_type', 2350555, 101, 'flow.company_project_status_type', 'project_status_type_id', 5);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (6, 'Project Stage', 'flow.project_status_type', 'project_status_type', 2350555, 15, 'flow.company_project_status_type', 'project_status_type_id', 5);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (56, 'Project Stage', 'flow.project_status_type', 'project_status_type', 2350555, 115, 'flow.company_project_status_type', 'project_status_type_id', 5);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (11, 'Project Stage', 'flow.project_status_type', 'project_status_type', 2350555, 25, 'flow.company_project_status_type', 'project_status_type_id', 5);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (76, 'Project Stage', 'flow.project_status_type', 'project_status_type', 2350555, 155, 'flow.company_project_status_type', 'project_status_type_id', 5);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (36, 'Project Stage', 'flow.project_status_type', 'project_status_type', 2350555, 65, 'flow.company_project_status_type', 'project_status_type_id', 5);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (61, 'Project Stage', 'flow.project_status_type', 'project_status_type', 2350555, 125, 'flow.company_project_status_type', 'project_status_type_id', 5);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (16, 'Project Stage', 'flow.project_status_type', 'project_status_type', 2350555, 35, 'flow.company_project_status_type', 'project_status_type_id', 5);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (66, 'Project Stage', 'flow.project_status_type', 'project_status_type', 2350555, 135, 'flow.company_project_status_type', 'project_status_type_id', 5);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (41, 'Project Stage', 'flow.project_status_type', 'project_status_type', 2350555, 85, 'flow.company_project_status_type', 'project_status_type_id', 5);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (21, 'Project Stage', 'flow.project_status_type', 'project_status_type', 2350555, 45, 'flow.company_project_status_type', 'project_status_type_id', 5);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (26, 'Project Stage', 'flow.project_status_type', 'project_status_type', 2350555, 55, 'flow.company_project_status_type', 'project_status_type_id', 5);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (71, 'Project Stage', 'flow.project_status_type', 'project_status_type', 2350555, 145, 'flow.company_project_status_type', 'project_status_type_id', 5);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (46, 'Project Stage', 'flow.project_status_type', 'project_status_type', 2350555, 95, 'flow.company_project_status_type', 'project_status_type_id', 5);

-- process step category fields
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES ( 4, 'Process Step Category', 'flow.process_step_status_type', 'process_step_status_type', 2350555, 1, 'flow.company_process_step_status_type', 'company_process_step_status_type_id', 4);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES ( 54, 'Process Step Category', 'flow.process_step_status_type', 'process_step_status_type', 2350555, 101, 'flow.company_process_step_status_type', 'company_process_step_status_type_id', 4);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (9, 'Process Step Category', 'flow.process_step_status_type', 'process_step_status_type', 2350555, 11, 'flow.company_process_step_status_type', 'company_process_step_status_type_id', 4);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (59, 'Process Step Category', 'flow.process_step_status_type', 'process_step_status_type', 2350555, 111, 'flow.company_process_step_status_type', 'company_process_step_status_type_id', 4);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (14, 'Process Step Category', 'flow.process_step_status_type', 'process_step_status_type', 2350555, 21, 'flow.company_process_step_status_type', 'company_process_step_status_type_id', 4);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (79, 'Process Step Category', 'flow.process_step_status_type', 'process_step_status_type', 2350555, 151, 'flow.company_process_step_status_type', 'company_process_step_status_type_id', 4);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (39, 'Process Step Category', 'flow.process_step_status_type', 'process_step_status_type', 2350555, 61, 'flow.company_process_step_status_type', 'company_process_step_status_type_id', 4);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (64, 'Process Step Category', 'flow.process_step_status_type', 'process_step_status_type', 2350555, 121, 'flow.company_process_step_status_type', 'company_process_step_status_type_id', 4);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (19, 'Process Step Category', 'flow.process_step_status_type', 'process_step_status_type', 2350555, 31, 'flow.company_process_step_status_type', 'company_process_step_status_type_id', 4);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (69, 'Process Step Category', 'flow.process_step_status_type', 'process_step_status_type', 2350555, 131, 'flow.company_process_step_status_type', 'company_process_step_status_type_id', 4);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (44, 'Process Step Category', 'flow.process_step_status_type', 'process_step_status_type', 2350555, 81, 'flow.company_process_step_status_type', 'company_process_step_status_type_id', 4);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (24, 'Process Step Category', 'flow.process_step_status_type', 'process_step_status_type', 2350555, 41, 'flow.company_process_step_status_type', 'company_process_step_status_type_id', 4);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (29, 'Process Step Category', 'flow.process_step_status_type', 'process_step_status_type', 2350555, 51, 'flow.company_process_step_status_type', 'company_process_step_status_type_id', 4);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (74, 'Process Step Category', 'flow.process_step_status_type', 'process_step_status_type', 2350555, 141, 'flow.company_process_step_status_type', 'company_process_step_status_type_id', 4);
INSERT INTO flow.smartlist_field (company_object_type_id, name, reference_table, reference_column, created_by_id, company_data_type_id, join_table, join_column, smartlist_system_list_id) VALUES (49, 'Process Step Category', 'flow.process_step_status_type', 'process_step_status_type', 2350555, 91, 'flow.company_process_step_status_type', 'company_process_step_status_type_id', 4);
