drop function if exists brs.get_calculated_proposal_values(integer, boolean);

drop type if exists brs.calculated_proposal_value;
create type brs.calculated_proposal_value as
(
  monthly_cost_25_year_average_without_solar             numeric,
  monthly_cost_30_year_average_without_solar             numeric,
  monthly_cost_25_year_average_with_solar                numeric,
  remaining_monthly_electric_bill_25_year_average        numeric,
  remaining_monthly_electric_bill_30_year_average        numeric,
  total_cost_25_years                                    numeric,
  total_cost_30_years                                    numeric,
  total_savings_25_years                                 numeric,
  total_savings_30_years                                 numeric,
  monthly_solar_payment                                  numeric,
  monthly_cost_today_without_solar                       numeric,
  monthly_cost_today_with_blue_power                     numeric,
  monthly_cost_today_avg_remaining_electrical_bill       numeric,
  monthly_payment_all_tax_credits_and_rebates_to_loan    numeric,
  monthly_payment_no_tax_credits_and_rebates_to_loan     numeric,
  monthly_payment_all_tax_credits_and_rebates_to_loan_19 numeric,
  monthly_payment_no_tax_credits_and_rebates_to_loan_19  numeric,
  monthly_payment_all_tax_credits_and_rebates_to_loan_26 numeric,
  monthly_payment_no_tax_credits_and_rebates_to_loan_26  numeric,
  system_size                                            numeric,
  first_year_production_estimate                         integer,
  total_system_cost                                      numeric,
  referral_promotion                                     numeric,
  total_loan_amount                                      numeric,
  federal_tax_incentive_amount                           numeric,
  federal_tax_incentive_rate                             numeric,
  net_system_cost                                        numeric,
  utility_company                                        text,
  estimated_annual_energy_consumption_kwh                integer,
  current_estimated_annual_utility_bill                  numeric,
  current_estimated_cost_per_kwh                         numeric,
  utility_cost_escalator                                 numeric,
  state_rebate_amount                                    numeric,
  eto_rebate                                             numeric,
  csu_rebate                                             numeric,
  apr                                                    numeric,
  loan_term                                              numeric,
  assumed_payment_by_month_18                            numeric,
  panel_degradation_factor                               numeric,
  system_production_25_year                              numeric,
  estimated_offset                                       numeric,
  led_light_bulbs                                        integer,
  smart_thermostat                                       integer,
  total_ee_reduction                                     numeric,
  panel_warranty                                         integer,
  inverter_warranty                                      integer,
  down_payment_amount                                    numeric,
  -- should be in the other type table
  version_id                                             integer,
  project_process_step_id                                integer,
  friends_and_family                                     boolean,
  production_factor                                      numeric,
  funding_range                                          numeric,
  production_factor_range                                numeric,
  points_off_south_production_factor                     numeric,
  price_change_per_production_point                      numeric,
  calculated_price_adjustment                            numeric,
  max_price_adjustment                                   numeric,
  adjusted_price_per_wat                                 numeric,
  initial_system_cost                                    numeric,
  promotion_cost                                         numeric,
  equipment_inverter_adder                               numeric,
  equipment_panel_adder                                  numeric,
  equipment_storage_adder                                numeric,
  misc_adders                                            numeric,
  panel_brand_id                                         integer,
  panel_watts                                            integer,
  above_line_rebate                                      numeric,
  state_id                                               integer,
  utility_company_id                                     integer,
  dealer_fee                                             numeric,
  eto_rebate_unit_type_id                                integer,
  federal_unit_type_id                                   integer,
  inverter_efficiency                                    numeric,
  initial_payment_factor                                 numeric,
  reamortization_factor                                numeric
);

drop type if exists brs.excluded_proposal_value;
create type brs.excluded_proposal_value as
(
  version_id                         integer,
  project_process_step_id            integer,
  friends_and_family                 boolean,
  production_factor                  numeric,
  funding_range                      numeric,
  production_factor_range            numeric,
  points_off_south_production_factor numeric,
  price_change_per_production_point  numeric,
  calculated_price_adjustment        numeric,
  max_price_adjustment               numeric,
  adjusted_price_per_wat             numeric,
  initial_system_cost                numeric,
  promotion_cost                     numeric,
  equipment_inverter_adder           numeric,
  equipment_panel_adder              numeric,
  equipment_storage_adder            numeric,
  misc_adders                        numeric,
  panel_brand_id                     integer,
  panel_watts                        integer,
  above_line_rebate                  numeric,
  state_id                           integer,
  utility_company_id                 integer,
  dealer_fee                         numeric,
  eto_rebate_unit_type_id            integer,
  federal_unit_type_id               integer,
  inverter_efficiency                numeric,
  initial_payment_factor             numeric,
  reamortization_factor            numeric
);

