CREATE TABLE IF NOT EXISTS brs.proposal_log
(
  id SERIAL NOT NULL,
  proposal_date date,
  source character varying(50),
  proposal json,
  project_id bigint,
  proposal_nbr integer,
  CONSTRAINT pk_proposal_log PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS pk_proposal_log
  ON brs.proposal_log (id);

CREATE INDEX IF NOT EXISTS proposal_log_proposal_date_idx
  ON brs.proposal_log (proposal_date);

create sequence if not exists brs.proposal_excel_id_seq START WITH 1000;

CREATE TABLE IF NOT EXISTS brs.proposal_log_history
(
    id                                          serial not null,
    filename                                    varchar(100),
    project_id                                  varchar(100),
    fullname                                    varchar(100),
    address                                     varchar(100),
    city                                        varchar(100),
    state                                       varchar(100),
    zip                                         varchar(100),
    phone                                       varchar(100),
    email                                       varchar(100),
    loan_type                                   varchar(100),
    loan_term                                   varchar(100),
    interest_rate                               varchar(100),
    optional_down_payment                       varchar(100),
    number_of_leds                              varchar(100),
    number_of_ecobees                           varchar(100),
    cost_per_kwh_before_solar                   varchar(100),
    cost_per_kwh_after_solar                    varchar(100),
    bp_plus_promotion                           varchar(100),
    velocity_marketing                          varchar(100),
    military_discount                           varchar(100),
    show_graph                                  varchar(100),
    year_1_kwh_output                           varchar(100),
    panel_number                                varchar(100),
    panel_wattage                               varchar(100),
    system_size                                 varchar(100),
    panel                                       varchar(100),
    number_of_inverters                         varchar(100),
    inverter_mfg                                varchar(100),
    inverter_default_model                      varchar(100),
    inverter_custom_getting                     varchar(100),
    number_of_monitors                          varchar(100),
    monitor                                     varchar(100),
    utility_name                                varchar(100),
    rate_structure                              varchar(100),
    total_yearly_usage_pre_solar                varchar(100),
    tile_roof_adder                             varchar(100),
    hidden_conduit_adder                        varchar(100),
    flat_roof_adder                             varchar(100),
    upsize_inverter                             varchar(100),
    extra_adder                                 varchar(100),
    option_3_adder                              varchar(100),
    extra_promotion_cost                        varchar(100),
    plane_1_number_of_panels                    varchar(100),
    plane_1_tsrf                                varchar(100),
    plane_2_number_of_panels                    varchar(100),
    plane_2_tsrf                                varchar(100),
    plane_3_number_of_panels                    varchar(100),
    plane_3_tsrf                                varchar(100),
    plane_4_number_of_panels                    varchar(100),
    plane_4_tsrf                                varchar(100),
    plane_5_number_of_panels                    varchar(100),
    plane_5_tsrf                                varchar(100),
    plane_6_number_of_panels                    varchar(100),
    plane_6_tsrf                                varchar(100),
    plane_7_number_of_panels                    varchar(100),
    plane_7_tsrf                                varchar(100),
    automatic_adder                             varchar(100),
    automatic_adder_cost                        varchar(100),
    tile_roof_adder_cost                        varchar(100),
    three_kw_adder                              varchar(100),
    three_kw_adder_cost                         varchar(100),
    four_kw_adder                               varchar(100),
    four_kw_adder_cost                          varchar(100),
    upsize_inverter_adder_cost                  varchar(100),
    panel_adder                                 varchar(100),
    panel_adder_cost                            varchar(100),
    flat_roof_adder_cost                        varchar(100),
    hidden_conduit_adder_cost                   varchar(100),
    total_adder_costs                           varchar(100),
    ee_cost_per_watt                            varchar(100),
    funding_amount                              varchar(100),
    loan_fundingw                               varchar(100),
    loan_cost_to_customer                       varchar(100),
    total_cost_to_customer                      varchar(100),
    offset_percent                              varchar(100),
    dealer_fee                                  varchar(100),
    utility_escalator                           varchar(100),
    solar_degradation                           varchar(100),
    home_appreciationw                          varchar(100),
    funding_cap                                 varchar(100),
    production_factor                           varchar(100),
    south_production                            varchar(100),
    south_production_dollarw                    varchar(100),
    eastwest_production                         varchar(100),
    eastwest_production_dollarw                 varchar(100),
    total_cost                                  varchar(100),
    down_payment_above_line_incentive           varchar(100),
    referral_promotion                          varchar(100),
    loan_funding_amount                         varchar(100),
    loan_amount                                 varchar(100),
    itc                                         varchar(100),
    state_tax_credit                            varchar(100),
    customer_oop_itc_only_applied               varchar(100),
    customer_oop_all_rebates_applied            varchar(100),
    average_monthly_usage_before_solar          varchar(100),
    average_monthly_power_costs_before_solar    varchar(100),
    average_monthly_usage_after_solar           varchar(100),
    average_monthly_solar_production            varchar(100),
    monthly_solar_costs                         varchar(100),
    average_monthly_leftover_utility_power_kwh  varchar(100),
    average_leftover_utility_rate               varchar(100),
    average_monthly_utility_cost_after_solar    varchar(100),
    average_monthly_power_cost_after_solar      varchar(100),
    total_monthly_savings                       varchar(100),
    current_monthly_consumption                 varchar(100),
    consumption_after_ee                        varchar(100),
    kwh_savings_from_ee                         varchar(100),
    percent_saving_from_ee                      varchar(100),
    current_yearly_consumption                  varchar(100),
    yearly_consumption_after_ee                 varchar(100),
    total_added_home_value_estimate             varchar(100),
    twenty_five_year_cost_of_power_before_solar varchar(100),
    twenty_five_energy_cost                     varchar(100),
    lifetime_savings                            varchar(100),
    twenty_five_year_remaining_utility_bill     varchar(100),
    twenty_five_year_production                 varchar(100),
    thirty_five_year_production                 varchar(100),
    thirty_five_year_solar_cost                 varchar(100),
    thirty_five_year_solar_cost_per_kwh         varchar(100),
    thirty_five_year_utility_usage              varchar(100),
    thirty_five_year_cost_before_solar          varchar(100),
    thirty_five_year_cost_per_kw_before_solar   varchar(100),
    current_utility_oet_rebate_per_watt         varchar(100),
    current_max_oet_rebate                      varchar(100),
    current_oet_rebate                          varchar(100),
    max_or_tax_credit                           varchar(100),
    current_or_tax_credit                       varchar(100),
    choice_pf                                   varchar(100),
    choice_payment                              varchar(100),
    month_eighteen_payment                      varchar(100),
    eighteen_plus_payment                       varchar(100),
    month_eighteen_payment_itc_only             varchar(100),
    eighteen_plus_payment_itc_only              varchar(100),
    month_eighteen_payment_all_incentives       varchar(100),
    eighteen_plus_payments_all_incentives       varchar(100),
    date_created                                varchar(100),
    promotion_eighteen_months_free              varchar(100),
    secondary_loan_amount                       varchar(100),
    salal_primary_loan_monthly_payment          varchar(100),
    salal_prmiary_loan_total_payment            varchar(100),
    salal_primary_loan_finance_charge           varchar(100),
    salal_primary_loan_total_sales_price        varchar(100),
    salal_secondary_loan_monthly_payment        varchar(100),
    salal_secondary_loan_total_payments         varchar(100),
    salal_secondary_loan_finance_charge         varchar(100),
    lead_source                                 varchar(100),
    non_standard_work                           varchar(100),
    proposal_date                               date,
    proposal_nbr                                integer,
    source                                      varchar(50),
    proposal_log_id                             integer,
    non_standard_work_2                         varchar(100),
    zip_code_zone                               varchar(100),
    proposal_owner                              varchar(100),
    non_standard_work_1                         varchar(100),
    non_standard_work_1_cost                    varchar(100),
    non_standard_work_2_cost                    varchar(100),
    non_standard_work_3                         varchar(100),
    non_standard_work_3_cost                    varchar(100),
    extra_adders_dollar_per_watt                varchar(100),
    bp_plus_amount                              varchar(100),
    project_owner                               varchar(200),
    cost_per_watt_adder                         varchar(50)  default NULL::character varying,
    eto_eligible_kw                             varchar(50)  default NULL::character varying,
    nv_energy_system_size_for_rebate            varchar(50)  default NULL::character varying,
    above_line_item_type                        varchar(100),
    state_incentive_type                        varchar(100),
    gallons_of_gasoline                         varchar(100),
    home_electricity_use_for_one_year           varchar(100),
    trees_growing_for_ten_years                 varchar(100),
    tons_of_waste_sent_to_landfill              varchar(100),
    is_epc                                      varchar(32)  default NULL::character varying,
    epc_price                                   varchar(32)  default NULL::character varying,
    aurora_design_id                            varchar(100) default NULL::character varying,
    five_year_payoff                            varchar(100),
    six_year_payoff                             varchar(100),
    seven_year_payoff                           varchar(100),
    eight_year_payoff                           varchar(100),
    nine_year_payoff                            varchar(100),
    ten_year_payoff                             varchar(100),
    eleven_year_payoff                          varchar(100),
    twelve_year_payoff                          varchar(100),
    thirteen_year_payoff                        varchar(100),
    fourteen_year_payoff                        varchar(100),
    fifteen_year_payoff                         varchar(100),
    twenty_year_payoff                          varchar(100),
    CONSTRAINT proposal_log_history_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS proposal_log_history_created_date_idx
  ON brs.proposal_log_history (date_created);

CREATE INDEX IF NOT EXISTS proposal_log_history_project_id_idx
  ON brs.proposal_log_history (project_id);

CREATE INDEX IF NOT EXISTS proposal_log_history_proposal_date_idx
  ON brs.proposal_log_history (proposal_date);

CREATE INDEX IF NOT EXISTS proposal_log_history_proposal_nbr_idx
  ON brs.proposal_log_history (proposal_nbr);

drop trigger if exists process_proposal_log_history on brs.proposal_log;

create trigger process_proposal_log_history
    after insert
    on brs.proposal_log
    for each row
execute procedure brs.process_proposal_log_history();
