drop table if exists brs.permit_pack_log cascade;
create table if not exists brs.permit_pack_log
(
  id                  bigint primary key not null generated always as identity,
  project_id          int                not null references flow.project (id),
  permit_pack_log_nbr int                not null generated always as IDENTITY (sequence name permit_pack_log_nbr_seq minvalue 1000 maxvalue 9999 cycle ),
  design_log_id       int                null references brs.design_log (id),
  permit_pack_date    date,
  source              varchar,
  design              jsonb,
  bom                 jsonb,
  date_created        timestamptz        not null default now()
);
create index if not exists idx_permit_pack_log_project_id on brs.permit_pack_log (project_id);
create index if not exists idx_permit_pack_log_design_log_id on brs.permit_pack_log (design_log_id);

drop table if exists brs.permit_pack_log_history;
create table if not exists brs.permit_pack_log_history
(
  id                                   bigint primary key not null generated always as identity,
  project_id                           int                not null references flow.project (id),
  permit_pack_log_id                   int                not null references brs.permit_pack_log (id),
  permit_pack_log_nbr                  int                not null,
  design_log_id                        int                null references brs.design_log (id),
  permit_pack_date                     date,
  number_of_modules_mp1                varchar(50),
  number_of_modules_mp2                varchar(50),
  number_of_modules_mp3                varchar(50),
  number_of_modules_mp4                varchar(50),
  number_of_modules_mp5                varchar(50),
  number_of_modules_mp6                varchar(50),
  number_of_modules_mp7                varchar(50),
  number_of_modules_mp8                varchar(50),
  azimuth_mp1                          varchar(50),
  azimuth_mp2                          varchar(50),
  azimuth_mp3                          varchar(50),
  azimuth_mp4                          varchar(50),
  azimuth_mp5                          varchar(50),
  azimuth_mp6                          varchar(50),
  azimuth_mp7                          varchar(50),
  azimuth_mp8                          varchar(50),
  pitch_mp1                            varchar(50),
  pitch_mp2                            varchar(50),
  pitch_mp3                            varchar(50),
  pitch_mp4                            varchar(50),
  pitch_mp5                            varchar(50),
  pitch_mp6                            varchar(50),
  pitch_mp7                            varchar(50),
  pitch_mp8                            varchar(50),
  tsrf_mp1                             varchar(50),
  tsrf_mp2                             varchar(50),
  tsrf_mp3                             varchar(50),
  tsrf_mp4                             varchar(50),
  tsrf_mp5                             varchar(50),
  tsrf_mp6                             varchar(50),
  tsrf_mp7                             varchar(50),
  tsrf_mp8                             varchar(50),
  mp1_roof_area                        varchar(50),
  mp2_roof_area                        varchar(50),
  mp3_roof_area                        varchar(50),
  mp4_roof_area                        varchar(50),
  mp5_roof_area                        varchar(50),
  mp6_roof_area                        varchar(50),
  mp7_roof_area                        varchar(50),
  mp8_roof_area                        varchar(50),
  panels_on_primary_structure          varchar(50),
  panels_on_detached_structure         varchar(50),
  aurora_url                           varchar,
  dc_system_size_kw                    varchar(50),
  total_annual_production              varchar(50),
  module                               varchar(50),
  module_count                         varchar(50),
  inverter                             varchar(50),
  ahj                                  varchar(50),
  utility                              varchar(50),
  roof_material                        varchar(50),
  number_of_stories                    varchar(50),
  pv_breaker_ocpd_rating               varchar(50),
  load_side_interconnection            varchar(50),
  interconnection                      varchar(50),
  non_standard_interconnection         varchar(50),
  placard_required                     varchar(50),
  reroof_required                      varchar(50),
  blocking_required                    varchar(50),
  trenching_required                   varchar(50),
  overhead_span                        varchar(50),
  exterior_conduit_required            varchar(50),
  primary_mounting_hardware            varchar(50),
  primary_attachment                   varchar(50),
  ac_disconnect_required               varchar(50),
  utility_pv_meter_required            varchar(50),
  primary_landscape_attachment_spacing varchar(50),
  primary_portrait_attachment_spacing  varchar(50),
  ac_disconnect_rating                 varchar(50),
  ac_disconnect_type                   varchar(50),
  sheathing_type                       varchar(50),
  framing_type                         varchar(50),
  sheathing_attachment_required        varchar(50),
  system_offset                        varchar(50),
  net_metering_rate                    varchar(50),
  primary_structure_roof_area          varchar(50),
  arrays_on_primary_structure          varchar(50),
  arrays_on_detached_structure         varchar(50),
  bom                                  jsonb,
  date_created                         timestamptz        not null default now()
);

create index if not exists idx_pplh_project_id on brs.permit_pack_log_history (project_id);
create index if not exists idx_pplh_permit_pack_log_id on brs.permit_pack_log_history (permit_pack_log_id);
create index if not exists idx_pplh_design_log_id on brs.permit_pack_log_history (design_log_id);

