query activeSalesMetroAreas($idInput: IdInput!) {
  activeSalesMetroAreas(input: $idInput) {
    active
    area
    areaAverageFds
    fdsLastThirtyDays
    finalDesignMinimum
    fixedGraceDays
    graceDays
    id
    salesAreaId
    salesMetroArea
  }
}
