query login($loginInput: LoginInput!) {
  login(input: $loginInput) {
    token
    success
    details {
      companyName
      firstName
      id
      lastName
      originatorDealSourceId
      originatorId
      permissions {
        id
        permissionName
        permissionCode
      }
      userBaseOid
      userHasOriginator
    }
  }
}
