query salesMetroAreas {
  salesMetroAreas {
    active
    area
    areaAverageFds
    fdsLastThirtyDays
    finalDesignMinimum
    fixedGraceDays
    graceDays
    id
    salesAreaId
    salesMetroArea
  }
}
