query userSearch($userSearchInput: UserSearchInput!) {
  userSearch(input: $userSearchInput) {
      accuityAppointmentId
      activePositions
      allFullRole
      applicationDate
      backgroundCheckDate
      backgroundCheckSubmittedDate
      baseContactCreatedDate
      cancelledBaseContactDate
      cancelledIsolvedDate
      cancelledMosaicDate
      cancelledTrumpiaDate
      compensationType
      compensationTypeId
      confidentialityAgreementDate
      corporateMeetingInviteSentDate
      deactivateBadgeRequestDate
      department
      departmentId
      dividendDate
      dividendSpoofDate
      docusignReceivedDate
      docusignRequestedDate
      docusignSavedDate
      driversLicenseNumber
      dropboxDate
      email
      emailOptOutDate
      emailRemovedDate
      emailSetupDate
      employeeHandbookSignedDate
      employeeId
      employmentType
      employmentTypeId
      endDate
      enterInSolvedDate
      enterInTimeforceDate
      exitInterviewDate
      expiryDate
      firstName
      fullName
      greenLightDate
      hat
      hireDate
      historicalOffice
      historicalRegionalOffice
      historicalRole
      humanityDate
      i9Date
      id
      ignitionDate
      itOnboardingCompleteDate
      itTerminationCompleteDate
      lastName
      managerFullName
      managerUserId
      mosaicDate
      newHireOrientationMeetingDate
      notes
      offerLetterDate
      office
      officeId
      onboardedBy
      onboardedByUserId
      oneroofDate
      organization
      organizationId
      parent
      password
      pendingTerminationDate
      personalEmail
      phoneDirectoryDate
      phoneExtension
      phoneNumber
      photoDate
      positionEndDate
      positionId
      positionName
      positionStartDate
      primaryFlag
      primaryFullRole
      quickbaseDate
      reHireDate
      recruitedBy
      recruitedByUserId
      referredBy
      referredByUserId
      region
      regionId
      removedBaseDate
      requestBaseDate
      requestSunopsApp
      rolePermission
      roles
      salesArea
      salesAreaId
      salesMetroArea
      salesMetroAreaId
      secondaryFullRole
      shirtSize
      startDate
      terminationDate
      terminationReason
      timesheetCancelDate
      timesheetsDate
      trumpiaDate
      tshirtHatDate
      userStatusType
      userStatusTypeId
      userUuid
      valid
      valuesMeetingAttendedDate
      valuesMeetingInviteSentDate
      voidedCheckDate
      w4Date
      welcomeEmailDate
  }
}
