
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Prometheus Build

on:
      push:
          branches:
              - "prometheus"


jobs:
    build:
        name: Package & Deploy
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            -   name: Cancel Previous Runs
                uses: styfle/cancel-workflow-action@0.6.0
                with:
                    access_token: ${{ github.token }}

            -   uses: actions/checkout@v2

            -   name: Configure AWS credentials
                uses: aws-actions/configure-aws-credentials@v1
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: us-east-1

            -   name: Login to Amazon ECR
                id: login-ecr
                uses: aws-actions/amazon-ecr-login@v1

            -   name: set env
                id: vars
                run: |
                    echo ::set-output name=github_short_sha::$(echo ${GITHUB_SHA:0:7})

            -   name: Build & Push Image
                id: build-image
                env:
                    ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                    ECR_REPOSITORY: prometheus-repo
                    IMAGE_TAG: ${{ steps.vars.outputs.github_short_sha }}
                run: |
                    docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f .aws/prometheus/Dockerfile .
                    docker push $ECR_REGISTRY/$ECR_REPOSITORY
                    docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                    echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

            -   name: Fill in the new image ID for App Fargate task definition
                id: app-task-def
                uses: aws-actions/amazon-ecs-render-task-definition@v1
                with:
                    task-definition: .aws/prometheus-definition.json
                    container-name: prometheus-container
                    image: ${{ steps.build-image.outputs.image }}

            -   name: Deploy App Fargate Task
                uses: aws-actions/amazon-ecs-deploy-task-definition@v1
                with:
                    task-definition: ${{ steps.app-task-def.outputs.task-definition }}
                    service: prometheus-service
                    cluster: prometheus-cluster
